'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2Z"/><path d="M9 3v16M15 5v16"/>',layers:'<path d="m12 3 10 5-10 5L2 8Z"/><path d="m2 12 10 5 10-5M2 16l10 5 10-5"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',extent:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/><circle cx="12" cy="12" r="4"/>',measure:'<path d="m3 16 13-13 5 5L8 21Z"/><path d="m8 11 3 3m0-6 3 3m0-6 3 3"/>',polygon:'<path d="m5 5 14 2-2 13L3 16Z"/><circle cx="5" cy="5" r="1.7"/><circle cx="19" cy="7" r="1.7"/><circle cx="17" cy="20" r="1.7"/><circle cx="3" cy="16" r="1.7"/>',box:'<path stroke-dasharray="3 3" d="M4 4h16v16H4Z"/>',circle:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="2"/><path d="M12 12h8"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',chart:'<path d="M4 3v18h17M8 16v-5m5 5V6m5 10V9"/>',save:'<path d="M5 3h12l4 4v14H3V3Z"/><path d="M7 3v6h10V3M7 21v-8h10v8"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',tool:'<path d="M14 5a6 6 0 0 0-7 8l-5 5 4 4 5-5a6 6 0 0 0 8-7l-4 3-4-4Z"/>',folder:'<path d="M3 5h7l2 3h9v12H3Z"/>',leaf:'<path d="M20 3C5 2 2 9 6 16s15 2 14-13Z"/><path d="M4 21 16 8"/>',flow:'<rect x="8" y="2" width="8" height="5" rx="1"/><rect x="2" y="17" width="7" height="5" rx="1"/><rect x="15" y="17" width="7" height="5" rx="1"/><path d="M12 7v5H5v5m7-5h7v5"/>',spark:'<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 3"/>',check:'<path d="m4 12 5 5L20 6"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',compare:'<path d="M12 2v20M8 6H3v12h5m8-12h5v12h-5"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',home:'<path d="m3 10 9-7 9 7v11H3Z"/><path d="M9 21v-8h6v8"/>'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.layers}</svg>`;
const navs=[['map','一张图'],['resources','资源中心'],['tools','工具中心'],['scenes','应用场景'],['tasks','工作台'],['operations','运营管理']];
const groups=[['自然资源调查','landUsePatch','construction','unused','changeSurvey'],['耕地保护','primeFarmland','farmlandRedline','farmlandQuality','linkLedger'],['生态保护与修复','forest','grassland','wetland','desert','ecoRedline','natureReserve','ecoFunctionZone','ecoRestoreZone'],['矿产资源','mineralBlock','miningRight','exploreRight','mineRestore'],['地质环境','geoHazard','geoRiskZone','groundwater','soilMonitor'],['基础地理','town','road','settle','relief']];
const scenarios=[
 {id:'steward',name:'自然资源大管家',en:'RESOURCE ATLAS',icon:'layers',description:'摸清资源家底，关联资产与变化。',layers:['landUsePatch','forest','grassland','wetland'],steps:['选择区域与资源','查看资源家底','定位变化对象','生成核查任务'],requirement:'3.1',defaultQuery:'土地利用'},
 {id:'planning',name:'国土空间规划',en:'SPATIAL PLANNING',icon:'map',description:'在空间底图上核对规划与现状。',layers:['landUsePatch','construction','ecoRedline'],steps:['确定规划范围','叠加管控图层','核对空间关系','登记核查意见'],requirement:'3.2',defaultQuery:'建设用地'},
 {id:'farmland',name:'耕地保护与国土绿化',en:'FARMLAND & ECOLOGY',icon:'leaf',description:'耕地图斑、质量监测与生态空间联动。',layers:['primeFarmland','farmlandQuality','ecoRedline'],steps:['定位耕地图斑','叠加生态管控','记录矛盾线索','派发核查任务'],requirement:'3.3',defaultQuery:'永久基本农田'},
 {id:'elements',name:'要素保障',en:'PROJECT SUPPORT',icon:'flow',description:'项目范围、资源条件与办理进度关联。',layers:['construction','primeFarmland','ecoRedline','geoHazard'],steps:['绘制项目范围','执行空间查询','汇总核查对象','提交协同任务'],requirement:'3.4',defaultQuery:'建设用地'},
 {id:'mining',name:'矿业权多级一体化审批',en:'MINING RIGHTS',icon:'folder',description:'矿业权位置、有效期与审查协同。',layers:['miningRight','exploreRight','mineRestore'],steps:['检索矿业权','查看证照属性','核对关联空间','登记审查任务'],requirement:'3.5',defaultQuery:'采矿权'}
];
const toolDefs=[['query','空间范围查询','绘制范围，查询相交对象','polygon'],['buffer','周边缓冲分析','设置距离，查找周边对象','circle'],['measure','距离与面积量算','在地图上连续选点量算','measure'],['coordinate','坐标定位与转换','经纬度与墨卡托坐标转换','pin'],['compare','图层卷帘对照','对照基础底图与专题图层','compare'],['import','导入空间范围','预览本地 GeoJSON 文件','folder']];
const STORE='nmg-onemap-upgrade-v1';
let saved={};try{saved=JSON.parse(localStorage.getItem(STORE)||'{}')}catch{}
const layers=NMG_LAYERS.map(l=>({...l,id:l.id.replace('nmg:',''),name:l.name.replace('（演示点位）','').replace('（示意）',''),features:l.features.map(f=>({...f,layerId:l.id.replace('nmg:',''),layerName:l.name}))}));
const byId=Object.fromEntries(layers.map(l=>[l.id,l]));
const allFeatures=layers.flatMap(l=>l.features);
const state={route:'map',active:new Set(['primeFarmland','ecoRedline','miningRight']),opacity:{},region:'',keyword:'',selected:null,resultRows:null,resultLabel:'当前可见图层',page:0,showResults:false,tool:'',draw:null,drawPoints:[],drawGeometry:null,drawLayer:null,inspector:'',resource:null,scene:new URLSearchParams(location.search).get('scene')||'steward',base:'terrain',catalogTab:'all',grouping:'theme',searchLayers:'',role:saved.role==='admin'?'admin':'analyst',requests:Array.isArray(saved.requests)?saved.requests:[],tasks:Array.isArray(saved.tasks)?saved.tasks:[],bookmarks:Array.isArray(saved.bookmarks)?saved.bookmarks:[],logs:Array.isArray(saved.logs)?saved.logs:[],imports:[],operations:Array.isArray(saved.operations)?saved.operations:[],messages:[],compare:100};
if(!scenarios.some(s=>s.id===state.scene))state.scene='steward';
let toastTimer, geoHighlight=null, detailHighlight=null;
const persist=()=>{try{localStorage.setItem(STORE,JSON.stringify({role:state.role,requests:state.requests,tasks:state.tasks,bookmarks:state.bookmarks,logs:state.logs.slice(-100),operations:state.operations}));}catch{toast('浏览器存储不可用，本次修改仅在当前页面保留。')}};
const stamp=()=>new Date().toLocaleString('zh-CN',{hour12:false});
function log(action){state.logs.push({time:stamp(),action,role:state.role==='admin'?'演示管理员':'业务人员'});persist()}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200)}
const layerColor=id=>({primeFarmland:'#ba923f',ecoRedline:'#c36452',miningRight:'#637a91',forest:'#438468',grassland:'#8aa678',wetland:'#69a3af',landUsePatch:'#ae9c62',construction:'#bc7c65'}[id]||byId[id]?.displayColor||'#648572');
function geometryFeature(f){return {type:'Feature',id:f.id,properties:{id:f.id,name:f.name,layer:f.layerName,region:f.region,county:f.county,...f.properties,source:'模拟演示数据'},geometry:f.geometry}}
const map=L.map('map',{zoomControl:false,attributionControl:true,minZoom:4,maxZoom:15,zoomSnap:.25,zoomDelta:.5,preferCanvas:false}).setView([44.9,111.8],5.25);
map.attributionControl.setPrefix('Leaflet');
L.control.scale({imperial:false,position:'bottomleft',maxWidth:100}).addTo(map);
map.createPane('terrain');map.getPane('terrain').style.zIndex=200;
map.createPane('boundary');map.getPane('boundary').style.zIndex=350;
map.createPane('business');map.getPane('business').style.zIndex=410;
map.createPane('labels');map.getPane('labels').style.zIndex=440;map.getPane('labels').style.pointerEvents='none';
const relief=L.imageOverlay('assets/relief.webp',[[37,97],[53.5,126.1]],{pane:'terrain',opacity:.88,attribution:'地形：本地 DEM · 边界：已有参考数据'}).addTo(map);
const clipRing=NMG_GEO.province.features[0].geometry.coordinates[0];
const mercLat=lat=>Math.log(Math.tan(Math.PI/4+lat*Math.PI/360));
const clipPoints=clipRing.map(p=>`${(p[0]-97)/29.1*100}% ${(mercLat(53.5)-mercLat(p[1]))/(mercLat(53.5)-mercLat(37))*100}%`).join(',');
relief.getElement().style.clipPath=`polygon(${clipPoints})`;
for(let lng=95;lng<=130;lng+=5)L.polyline([[34,lng],[57,lng]],{pane:'terrain',color:'#91a68a',opacity:.16,weight:.6,interactive:false}).addTo(map);
for(let lat=36;lat<=56;lat+=4)L.polyline([[lat,94],[lat,130]],{pane:'terrain',color:'#91a68a',opacity:.16,weight:.6,interactive:false}).addTo(map);
const province=L.geoJSON(NMG_GEO.province,{pane:'boundary',style:{color:'#69846a',weight:1.7,fillColor:'#edf0de',fillOpacity:.05},interactive:false}).addTo(map);
function regionStyle(feature){const selected=feature.properties.name===state.region;return {color:selected?'#246b50':'#90a28a',weight:selected?2.5:.75,fillColor:'#6b9f79',fillOpacity:selected?.1:0};}
const cities=L.geoJSON(NMG_GEO.cities,{pane:'boundary',style:regionStyle,onEachFeature:(f,l)=>{l.on('click',e=>{if(state.draw)return;L.DomEvent.stopPropagation(e);selectRegion(f.properties.name)});l.bindTooltip(esc(f.properties.name),{sticky:true,className:'feature-tip'})}}).addTo(map);
const counties=L.geoJSON(NMG_GEO.counties,{pane:'boundary',style:{color:'#a8b7a1',weight:.55,fillOpacity:0},interactive:false});
NMG_GEO.centers.features.forEach(f=>L.circleMarker([f.geometry.coordinates[1],f.geometry.coordinates[0]],{pane:'labels',radius:2.5,color:'#648066',weight:1,fillOpacity:.9,interactive:false}).bindTooltip(esc(f.properties.name),{permanent:true,direction:'right',offset:[5,0],className:'city-label'}).addTo(map));
const mapLayers={};
function visibleFeatures(){return allFeatures.filter(f=>state.active.has(f.layerId)&&(!state.region||f.region===state.region))}
function filteredLayer(l){return l.features.filter(f=>!state.region||f.region===state.region)}
function refreshMap(){
 cities.setStyle(regionStyle);
 if(state.selected&&(!state.active.has(state.selected.layerId)||(state.region&&state.selected.region!==state.region))){state.selected=null;if(detailHighlight){map.removeLayer(detailHighlight);detailHighlight=null}if(state.inspector==='feature')closePanel();}
 for(const l of layers){if(mapLayers[l.id]){map.removeLayer(mapLayers[l.id]);delete mapLayers[l.id]}if(!state.active.has(l.id))continue;const c=layerColor(l.id),opacity=state.opacity[l.id]??.65;
  const fl=L.geoJSON({type:'FeatureCollection',features:filteredLayer(l).map(geometryFeature)},{pane:'business',style:{color:c,weight:1.25,opacity,fillOpacity:opacity*.27},pointToLayer:(f,latlng)=>L.circleMarker(latlng,{pane:'business',radius:4,color:'#fff',weight:1,fillColor:c,fillOpacity:opacity}),onEachFeature:(f,shape)=>{const original=l.features.find(x=>x.id===f.id);shape.on('click',e=>{if(state.draw)return;L.DomEvent.stopPropagation(e);selectFeature(original)});shape.bindTooltip(esc(f.properties.name),{sticky:true,className:'feature-tip'})}}).addTo(map);mapLayers[l.id]=fl;
 }
 renderLegend();updateAssistantContext();if(state.showResults&&state.resultRows===null)renderResults();if(state.inspector==='overview')showOverview();updateClip();
}
function fitAll(){map.fitBounds(province.getBounds(),{paddingTopLeft:[20,80],paddingBottomRight:state.inspector?[325,65]:[25,60],animate:false});}
function selectRegion(name){state.region=name||'';$('#region').value=state.region;state.resultRows=null;state.page=0;refreshMap();if(name){const f=NMG_GEO.cities.features.find(x=>x.properties.name===name);if(f)map.fitBounds(L.geoJSON(f).getBounds(),{padding:[60,90],maxZoom:9,animate:false});}else fitAll();if(state.route==='resources')renderSidebar();}
function renderLegend(){const selected=layers.filter(l=>state.active.has(l.id));$('#map-legend').innerHTML=`<h3>已叠加图层 · ${selected.length}</h3>${selected.slice(0,6).map(l=>`<div class="legend-row"><i style="color:${layerColor(l.id)};background:${layerColor(l.id)}40"></i>${esc(l.name)}</div>`).join('')}${selected.length>6?`<small>另有 ${selected.length-6} 个图层</small>`:''}${!selected.length?'<small>从左侧目录选择图层</small>':''}`;}
function setLayers(ids){state.active=new Set(ids);state.resultRows=null;state.page=0;refreshMap();renderSidebar();}
function toggleLayer(id){state.active.has(id)?state.active.delete(id):state.active.add(id);state.resultRows=null;refreshMap();renderSidebar();}
function head(title,en,desc){return `<div class="sidebar-head"><span class="eyebrow">${en}</span><h2>${title}</h2><p>${desc}</p></div>`}
function renderNav(){ $('#main-nav').innerHTML=navs.map(([id,name])=>`<button class="nav-item ${state.route===id?'active':''}" data-route="${id}" ${state.route===id?'aria-current="page"':''}>${name}</button>`).join('');}
function treeHTML(){const query=state.searchLayers.trim();let rows=groups.map(([name,...ids])=>[name,...ids.filter(id=>(!query||byId[id].name.includes(query))&&(state.catalogTab!=='active'||state.active.has(id)))]).filter(g=>g.length>1);
 if(state.grouping==='region')rows=[[(state.region||'内蒙古自治区')+' · 数据目录',...rows.flatMap(g=>g.slice(1))]];
 if(state.grouping==='department')rows=[['自然资源业务资料 · 演示目录',...rows.flatMap(g=>g.slice(1))]];
 return rows.map(([name,...ids],i)=>`<details class="tree-group" ${query||state.catalogTab==='active'||state.grouping!=='theme'||i<3?'open':''}><summary>${name}<small>${ids.length.toString().padStart(2,'0')}</small></summary>${ids.map(id=>`<div class="layer-row"><label><input type="checkbox" data-layer="${id}" ${state.active.has(id)?'checked':''}><span class="layer-symbol" style="color:${layerColor(id)}"></span><span class="layer-name">${esc(byId[id].name)}</span></label><button class="layer-info" data-action="resource" data-id="${id}" aria-label="${esc(byId[id].name)}图层详情">ⓘ</button></div>${state.catalogTab==='active'?`<div class="layer-controls"><span>透明度</span><input type="range" min="10" max="100" value="${(state.opacity[id]??.65)*100}" aria-label="${esc(byId[id].name)}不透明度" data-opacity="${id}"></div>`:''}`).join('')}</details>`).join('')||'<p class="empty-text">没有匹配的图层。<br>请换一个关键词。</p>';
}
function renderSidebar(){const el=$('#sidebar');
 if(state.route==='map')el.innerHTML=head('图层目录','SPATIAL CATALOG','统一底图，让资源与业务在此相遇。')+`<div class="sidebar-search"><input id="layer-search" placeholder="搜索图层名称" aria-label="搜索图层名称" value="${esc(state.searchLayers)}"></div><div class="sidebar-tabs"><button data-catalog="all" class="${state.catalogTab==='all'?'active':''}">全部图层</button><button data-catalog="active" class="${state.catalogTab==='active'?'active':''}">已加载 ${state.active.size}</button></div><div class="tree" id="layer-tree">${treeHTML()}</div><div class="sidebar-foot"><span>本地目录 · ${layers.length} 个图层</span><button data-action="clear-layers">清空叠加</button></div>`;
 if(state.route==='resources')el.innerHTML=head('资源中心','RESOURCE EXPLORER','查找资源、预览空间范围、申请使用。')+`<div class="sidebar-search"><input id="resource-search" placeholder="搜索资源名称" aria-label="搜索资源名称" value="${esc(state.searchLayers)}"></div><div class="chip-row" style="padding:0 18px 12px"><button class="chip ${state.grouping==='theme'?'active':''}" data-group="theme">主题</button><button class="chip ${state.grouping==='region'?'active':''}" data-group="region">地区</button><button class="chip ${state.grouping==='department'?'active':''}" data-group="department">部门</button></div><div class="side-list" id="resource-list">${resourceList()}</div><div class="sidebar-foot"><span>空间数据 · 本地预览</span><button data-action="requests">我的申请 ${state.requests.length}</button></div>`;
 if(state.route==='tools')el.innerHTML=head('空间工具箱','SPATIAL TOOLKIT','选定空间对象，直接在地图上分析。')+`<div class="side-list">${toolDefs.map(([id,name,desc,i])=>`<button class="side-item ${state.tool===id?'active':''}" data-tool="${id}">${icon(i)}<span><strong>${name}</strong><small>${desc}</small></span><span class="arrow">›</span></button>`).join('')}</div><div class="sidebar-foot"><span>量算采用球面近似</span><span>6 项工具</span></div>`;
 if(state.route==='scenes')el.innerHTML=head('业务应用场景','BUSINESS SCENARIOS','围绕业务问题，组织图层与办理路径。')+`<div class="side-list">${scenarios.map(s=>`<button class="side-item ${state.scene===s.id?'active':''}" data-scene="${s.id}">${icon(s.icon)}<span><strong>${s.name}</strong><small>${s.description}</small></span></button>`).join('')}</div><div class="sidebar-foot"><span>5 个场景 · 主流程原型</span><button data-action="saved-scene">保存当前组合</button></div>`;
 if(state.route==='tasks')el.innerHTML=head('我的工作台','MY WORKSPACE','从任务出发，回到具体的空间对象。')+`<div class="side-list"><button class="side-item active" data-action="tasks">${icon('clock')}<span><strong>空间核查任务</strong><small>${state.tasks.filter(t=>t.status!=='已办结').length} 项待办 · ${state.tasks.length} 项全部</small></span></button><button class="side-item" data-action="requests">${icon('folder')}<span><strong>资源使用申请</strong><small>申请、审核、下载记录</small></span></button><button class="side-item" data-action="bookmarks">${icon('save')}<span><strong>视图与场景书签</strong><small>保存区域、图层与观察位置</small></span></button><button class="side-item" data-action="logs">${icon('clock')}<span><strong>本地操作记录</strong><small>追溯当前浏览器内的业务操作</small></span></button></div><div class="sidebar-foot"><span>浏览器本地保存</span><span>刷新后可恢复</span></div>`;
 if(state.route==='operations')el.innerHTML=head('数据运营','DATA OPERATIONS','沿数据流转路径组织治理与发布。')+`<div class="side-list"><button class="side-item active" data-action="operations">${icon('flow')}<span><strong>归集与发布流水线</strong><small>登记 → 质检 → 编目 → 发布</small></span></button><button class="side-item" data-action="approvals">${icon('check')}<span><strong>使用申请审核</strong><small>受控资源使用期限与审批状态</small></span></button><button class="side-item" data-action="catalog-admin">${icon('layers')}<span><strong>图层资产目录</strong><small>查看元数据与几何类型</small></span></button><button class="side-item" data-action="logs">${icon('clock')}<span><strong>操作记录</strong><small>本地事件时间线</small></span></button><button class="side-item" data-action="integration-monitor">${icon('chart')}<span><strong>接入与监测说明</strong><small>生产服务接入设计边界</small></span></button></div><div class="sidebar-foot"><span>本地流程原型</span><button data-action="identity">切换演示身份</button></div>`;
}
function resourceList(){const matching=layers.filter(l=>!state.searchLayers||l.name.includes(state.searchLayers));const title=state.grouping==='region'?(state.region||'内蒙古自治区'):state.grouping==='department'?'自然资源业务资料 · 部门归属待接入':'空间图层';return `<p class="note" style="margin:4px 9px 8px">${title} · ${matching.length} 项</p>`+matching.map(l=>`<button class="side-item ${state.resource===l.id?'active':''}" data-action="resource" data-id="${l.id}"><span class="layer-symbol" style="color:${layerColor(l.id)};margin-top:5px"></span><span><strong>${esc(l.name)}</strong><small>${filteredLayer(l).length} 个对象 · ${l.features[0]?.geometry.type==='Point'?'点':'空间要素'} · 示例数据</small></span><span class="arrow">›</span></button>`).join('')}
function panel(title,en,body,footer='',kind='detail'){if(innerWidth<681)$('#sidebar').classList.add('mobile-hidden');state.inspector=kind;$('#inspector').hidden=false;$('#inspector').innerHTML=`<div class="inspector-header"><span class="eyebrow">${en}</span><h2>${title}</h2><button class="close-button" data-action="close-panel" aria-label="关闭详情面板">${icon('close')}</button></div><div class="inspector-body">${body}</div>${footer?`<div class="inspector-footer">${footer}</div>`:''}`;}
function closePanel(){state.inspector='';$('#inspector').hidden=true;}
function showOverview(){const list=visibleFeatures();const rankings=layers.filter(l=>state.active.has(l.id)).map(l=>({name:l.name,count:filteredLayer(l).length,color:layerColor(l.id)})).sort((a,b)=>b.count-a.count);const max=Math.max(1,...rankings.map(l=>l.count));panel('区域资源概览','REGIONAL OVERVIEW',`<div class="metric-line"><strong>${list.length.toLocaleString()}</strong><small>个可见对象</small></div><div class="stat-pair"><div><strong>${state.active.size.toString().padStart(2,'0')}</strong><small>已叠加专题图层</small></div><div><strong>${state.region?'01':'12'}</strong><small>当前盟市范围</small></div></div><h3>${state.region||'内蒙古自治区'}</h3><p class="note" style="margin-top:0">按当前图层和行政区动态统计对象数量。</p>${rankings.map(l=>`<div class="distribution-row"><div><span>${l.name}</span><span>${l.count}</span></div><div class="bar"><i style="width:${l.count/max*100}%;background:${l.color}"></i></div></div>`).join('')}<div class="hint">在地图上选择一个对象，即可查看属性、定位关联资源或发起核查任务。</div><p class="note">以上为本地模拟对象数量，不代表自治区资源家底总量。</p>`,`<button class="secondary wide" data-action="show-results">${icon('layers')} 查看属性表</button>`,'overview')}
function showResource(id){const l=byId[id];if(!l)return;state.resource=id;state.selected=null;const types=[...new Set(l.features.map(f=>f.geometry.type))];panel(esc(l.name),'RESOURCE METADATA',`<span class="tag">空间图层</span> <span class="tag gray">模拟示例</span><dl class="properties"><div><dt>对象数量</dt><dd>${filteredLayer(l).length} / ${l.features.length}</dd></div><div><dt>空间范围</dt><dd>${state.region||'内蒙古自治区'}</dd></div><div><dt>几何类型</dt><dd>${types.join(' / ')}</dd></div><div><dt>来源</dt><dd>既有 demo / oneMap 运行数据</dd></div><div><dt>坐标处理</dt><dd>沿用已有近似转换经纬度</dd></div><div><dt>使用范围</dt><dd>本地原型演示</dd></div><div><dt>更新方式</dt><dd>示例数据，未接入生产服务</dd></div></dl><h3>地图显示</h3><label class="field">图层不透明度<input type="range" min="10" max="100" value="${(state.opacity[id]??.65)*100}" data-opacity="${id}" aria-label="图层不透明度"></label><button class="secondary wide" data-action="preview-resource" data-id="${id}">${icon('eye')} 预览并查看属性</button><p class="note">点数据保留点几何，不作为矿权或建设用地的真实边界。</p>`,`<button class="primary" style="flex:1" data-action="request-resource" data-id="${id}">申请示例数据</button><button class="secondary" data-action="toggle-resource" data-id="${id}">${state.active.has(id)?'移除图层':'叠加图层'}</button>`,'resource');if(state.route==='resources')renderSidebar();}
function selectFeature(f){if(!f)return;state.selected=f;updateAssistantContext();if(detailHighlight)map.removeLayer(detailHighlight);detailHighlight=L.geoJSON(geometryFeature(f),{interactive:false,style:{color:'#164d3b',weight:3,fillOpacity:.15},pointToLayer:(x,ll)=>L.circleMarker(ll,{radius:8,color:'#164d3b',weight:2,fillColor:'#fff',fillOpacity:.5})}).addTo(map);const p=f.properties,c=Spatial.center(f.geometry);panel(esc(f.name),'FEATURE INSPECTOR',`<span class="tag">${esc(f.layerName)}</span><dl class="properties"><div><dt>对象编号</dt><dd>${esc(f.id)}</dd></div><div><dt>所在区域</dt><dd>${esc(f.region)} / ${esc(f.county||'—')}</dd></div><div><dt>几何类型</dt><dd>${f.geometry.type==='Point'?'点位示例':f.geometry.type==='LineString'?'线状示例':'面状示例'}</dd></div><div><dt>登记面积</dt><dd>${f.area!=null?Number(f.area).toLocaleString()+' '+esc(f.unit):'未提供'}</dd></div><div><dt>数据年度</dt><dd>${esc(p.year||'未提供')}</dd></div><div><dt>业务状态</dt><dd>${esc(p.approval||'未提供')}</dd></div>${p.validUntil?`<div><dt>有效期至</dt><dd>${esc(p.validUntil)}</dd></div>`:''}<div><dt>示例责任单位</dt><dd>${esc(p.owner||'未提供')}</dd></div><div><dt>中心位置</dt><dd>${c[0].toFixed(5)}°, ${c[1].toFixed(5)}°</dd></div></dl>${p.control?`<h3>源数据中的业务说明</h3><p class="note">${esc(p.control)}</p>`:''}<div class="hint">${f.geometry.type==='Point'?'本对象仅为位置示例，登记面积是属性值，不由点几何计算。':'登记面积沿用示例属性，与几何量算结果可能不一致。'}</div>`,`<button class="primary" data-action="task-new">创建核查任务</button><button class="secondary" data-action="locate-selected">${icon('pin')} 定位</button>`,'feature');}
function locateFeature(f){if(!f)return;selectFeature(f);const b=Spatial.bbox(f.geometry);map.fitBounds([[b[1],b[0]],[b[3],b[2]]],{paddingTopLeft:[50,50],paddingBottomRight:[350,state.showResults?280:60],maxZoom:f.geometry.type==='Point'?10:11,animate:false});}
function resultData(){return state.resultRows===null?visibleFeatures():state.resultRows;}
function showResults(rows=null,label='当前可见图层'){state.resultRows=rows;state.resultLabel=label;state.page=0;state.showResults=true;renderResults();}
function renderResults(){const el=$('#results');el.hidden=!state.showResults;$('.map-workspace').classList.toggle('has-results',state.showResults);if(!state.showResults)return;const rows=resultData(),size=20,pages=Math.max(1,Math.ceil(rows.length/size));state.page=Math.min(state.page,pages-1);const slice=rows.slice(state.page*size,(state.page+1)*size);el.innerHTML=`<div class="results-header"><strong>属性与查询结果</strong><small>${esc(state.resultRows===null?(state.region?state.region+' · ':'')+'当前可见图层':state.resultLabel)} · ${rows.length} 项</small><div class="right"><button class="text-button" data-action="fit-results">范围定位</button><button class="text-button" data-action="export-csv">${icon('download')} 导出本页</button><button data-action="close-results" aria-label="关闭属性表">${icon('close')}</button></div></div><div class="results-table">${rows.length?`<table><thead><tr><th>对象编号</th><th>名称</th><th>图层</th><th>盟市 / 旗县</th><th>登记面积</th><th>状态</th><th>操作</th></tr></thead><tbody>${slice.map(f=>`<tr><td>${esc(f.id)}</td><td><button data-action="select-feature" data-id="${f.id}">${esc(f.name)}</button></td><td>${esc(f.layerName)}</td><td>${esc(f.region)} / ${esc(f.county||'—')}</td><td>${f.area!=null?Number(f.area).toLocaleString()+' '+esc(f.unit):'—'}</td><td>${esc(f.properties.approval||'—')}</td><td><button data-action="locate-feature" data-id="${f.id}">定位 ↗</button></td></tr>`).join('')}</tbody></table>`:'<div class="results-empty">没有匹配对象。请扩大范围、切换图层或调整查询条件。</div>'}</div><div class="results-footer"><span>地图与属性表联动 · 模拟数据，登记面积不作为测绘成果</span><span><button data-action="page-prev" ${state.page===0?'disabled':''}>上一页</button>${state.page+1} / ${pages}<button data-action="page-next" ${state.page===pages-1?'disabled':''}>下一页</button></span></div>`;}
function fitFeatures(rows){if(!rows.length){toast('当前没有可定位的对象');return}let b=[180,90,-180,-90];rows.forEach(f=>{const x=Spatial.bbox(f.geometry);b=[Math.min(b[0],x[0]),Math.min(b[1],x[1]),Math.max(b[2],x[2]),Math.max(b[3],x[3])]});map.fitBounds([[b[1],b[0]],[b[3],b[2]]],{paddingTopLeft:[40,100],paddingBottomRight:[state.inspector?330:70,state.showResults?280:80],maxZoom:10,animate:false});}
function search(query){query=query.trim();if(!query){state.resultRows=null;showResults();return}const city=NMG_GEO.cities.features.find(f=>query===f.properties.name||query===f.properties.name.replace(/市$|盟$/,''));if(city){selectRegion(city.properties.name);showResults(null,city.properties.name);toast('已定位至'+city.properties.name);return}const matches=allFeatures.filter(f=>(!state.region||f.region===state.region)&&[f.id,f.name,f.layerName,f.region,f.county].some(x=>String(x).includes(query)));matches.forEach(f=>state.active.add(f.layerId));refreshMap();renderSidebar();showResults(matches,'搜索：'+query);if(matches.length)fitFeatures(matches);}
function openTool(id){state.tool=id;renderSidebar();cancelDraw();if(id!=='compare')stopCompare();
 if(id==='query')panel('空间范围查询','SPATIAL QUERY',`<p>用一个范围，找到当前图层中与其相交的对象。</p><h3>选择范围方式</h3><button class="primary wide" data-action="draw-query">${icon('polygon')} 在地图上绘制多边形</button><button class="secondary wide" style="margin-top:8px" data-action="draw-box">${icon('box')} 两点框选范围</button><h3>参与查询的图层</h3><p class="note">当前 ${state.active.size} 个可见图层；可切换至“一张图”调整。</p><div class="hint">点击地图添加顶点，至少 3 点后点击“完成”。Esc 取消；重新绘制会清除上次范围。</div><p class="note">对示例点、线、面执行几何相交查询。结果仅表示空间关系，不构成合规审查结论。</p>`, '', 'tool');
 if(id==='buffer')panel('周边缓冲分析','BUFFER ANALYSIS',`<p>选择中心点与距离，查找当前图层内的周边对象。</p><label class="field">中心点来源<select id="buffer-source"><option value="map">在地图上选择</option>${state.selected?'<option value="selected">当前选中对象的中心</option>':''}</select></label><label class="field">缓冲距离（公里）<input id="buffer-distance" type="number" min="0.1" max="300" step="0.1" value="10"></label><button class="primary wide" data-action="buffer-start">${icon('circle')} 开始周边分析</button><p class="note">使用球面缓冲范围，以 96 段多边形近似。多边形或线与范围相交即进入结果；距离不作为精密测量成果。</p>`, '', 'tool');
 if(id==='measure')panel('地图量算','GEOGRAPHIC MEASUREMENT',`<p>沿路径选点测距离，或闭合多边形测面积。</p><div class="field"><button class="primary wide" data-action="draw-distance">${icon('measure')} 测量距离</button><button class="secondary wide" data-action="draw-area">${icon('polygon')} 测量面积</button></div><div id="measure-result" class="hint">绘制后在这里显示计算结果。</div><p class="note">距离使用球面大圆距离；面积采用球面近似。地图显示坐标沿用既有 demo 的近似转换结果。</p>`, '', 'tool');
 if(id==='coordinate')panel('坐标定位与转换','COORDINATE TOOLS',`<form id="coordinate-form"><label class="field">经度（-180° 至 180°）<input id="coord-lng" type="number" step="any" min="-180" max="180" value="111.67" required></label><label class="field">纬度（-85° 至 85°）<input id="coord-lat" type="number" step="any" min="-85" max="85" value="40.82" required></label><button class="primary wide" type="submit">转换并定位</button></form><div id="coordinate-result" class="hint">经纬度 → Web Mercator（EPSG:3857）</div><p class="note">此工具不进行 GCJ-02、CGCS2000 高精度转换，也不代替测绘转换参数。</p>`, '', 'tool');
 if(id==='compare'){panel('专题图层卷帘','LAYER COMPARISON',`<p>滑动分隔线，对照基础底图和当前专题图层。</p><div class="hint">左侧：自然地理底图<br>右侧：已叠加的业务专题</div><p class="note">这是同一时点的图层对照。当前未提供经过核验的多期影像，不能用于认定历史变化。</p><button class="secondary wide" data-action="compare-stop">结束卷帘</button>`,'','tool');state.compare=50;const bar=document.createElement('div');bar.id='compare-control';bar.className='compare-control';bar.innerHTML='<label for="compare-range"><span>基础底图</span><span>业务专题</span></label><input id="compare-range" type="range" min="0" max="100" value="50" aria-label="卷帘分隔位置">';$('.map-workspace').append(bar);updateClip();}
 if(id==='import')panel('导入空间范围','GEOJSON PREVIEW',`<p>在本机读取 GeoJSON，并叠加到当前地图。</p><label class="field">选择文件（最大 5 MB）<input class="file-input" id="geojson-file" type="file" accept=".json,.geojson,application/geo+json,application/json"></label><div class="hint">支持 Point、LineString、Polygon 及其 Multi 类型；坐标必须是经度、纬度顺序。最多 1,000 个对象。</div><div id="import-result"></div><p class="note">文件仅在浏览器中读取，不上传。导入图层用于预览，尚未进入资源编目与业务审批。</p>`,'','tool');
}
function cancelDraw(){state.draw=null;state.drawPoints=[];$('#drawing-hint').hidden=true;$('.map-workspace').classList.remove('drawing');map.doubleClickZoom.enable();$$('#map-tools button').forEach(b=>b.classList.remove('active'));}
function startDraw(mode){cancelDraw();state.drawGeometry=null;updateAssistantContext();if(geoHighlight){map.removeLayer(geoHighlight);geoHighlight=null}state.draw=mode;state.drawPoints=[];$('#drawing-hint').hidden=false;const prompts={box:'在地图上点击两个对角点',buffer:'在地图上点击缓冲中心',query:'点击地图添加顶点',area:'点击地图添加面积范围顶点',distance:'点击地图添加路径点'};$('#drawing-hint').innerHTML=`${prompts[mode]}${['query','area','distance'].includes(mode)?'<button data-action="finish-draw">完成绘制</button><button data-action="undo-draw">撤销一点</button>':''}<button data-action="cancel-draw">取消 / Esc</button>`;$('.map-workspace').classList.add('drawing');map.doubleClickZoom.disable();if(innerWidth<681)$('#inspector').hidden=true;toast(prompts[mode]);}
function drawPreview(){if(geoHighlight)map.removeLayer(geoHighlight);if(!state.drawPoints.length)return;geoHighlight=L.featureGroup();if(state.drawPoints.length>1)L.polyline(state.drawPoints.map(p=>[p[1],p[0]]),{color:'#194f3b',weight:2,dashArray:'5 4'}).addTo(geoHighlight);state.drawPoints.forEach(p=>L.circleMarker([p[1],p[0]],{radius:4,color:'#194f3b',fillColor:'#fff',fillOpacity:1,weight:2}).addTo(geoHighlight));geoHighlight.addTo(map);}
function showGeometry(g){if(geoHighlight)map.removeLayer(geoHighlight);geoHighlight=L.geoJSON(g,{style:{color:'#194f3b',weight:2,dashArray:'6 4',fillColor:'#649c76',fillOpacity:.13}}).addTo(map);state.drawGeometry=g;updateAssistantContext();}
function runGeometryQuery(g,label){showGeometry(g);const matches=visibleFeatures().filter(f=>Spatial.intersects(f.geometry,g));showResults(matches,label);toast(`空间查询完成，找到 ${matches.length} 个对象`);log(label+'，匹配 '+matches.length+' 个模拟对象');}
function finishDraw(){const mode=state.draw,pts=[...state.drawPoints];if(mode==='distance'&&pts.length<2||mode!=='distance'&&pts.length<3){toast(mode==='distance'?'至少需要 2 个点':'至少需要 3 个点');return}if(mode!=='distance'){
 const ring=[...pts,pts[0]];for(let i=0;i<ring.length-1;i++)for(let j=i+2;j<ring.length-1;j++){if(i===0&&j===ring.length-2)continue;const a={type:'LineString',coordinates:[ring[i],ring[i+1]]},b={type:'LineString',coordinates:[ring[j],ring[j+1]]};if(Spatial.intersects(a,b)){toast('范围发生自相交，请撤销顶点后重新绘制');return}}
 }
 cancelDraw();if(innerWidth<681&&state.inspector)$('#inspector').hidden=false;
 if(mode==='distance'){const d=pts.slice(1).reduce((s,p,i)=>s+Spatial.distance(pts[i],p),0);showGeometry({type:'LineString',coordinates:pts});const text=`距离 ${(d/1000).toFixed(3)} 公里（球面近似）`;if($('#measure-result'))$('#measure-result').textContent=text;toast(text);return}
 const g={type:'Polygon',coordinates:[[...pts,pts[0]]]};if(Spatial.area(g)<1){toast('范围面积过小，请重新绘制');return}if(mode==='area'){showGeometry(g);const text=`面积 ${(Spatial.area(g)/10000).toLocaleString('zh-CN',{maximumFractionDigits:2})} 公顷（球面近似）`;if($('#measure-result'))$('#measure-result').textContent=text;toast(text);}else runGeometryQuery(g,'绘制范围相交查询');
}
map.on('click',e=>{if(!state.draw)return;const p=[e.latlng.lng,e.latlng.lat];if(state.draw==='buffer'){const radius=state.bufferRadius;cancelDraw();if(state.inspector)$('#inspector').hidden=false;runGeometryQuery(Spatial.circle(p,radius*1000),'周边 '+radius+' 公里');return}state.drawPoints.push(p);if(state.draw==='box'&&state.drawPoints.length===2){const [a,b]=state.drawPoints;cancelDraw();if(state.inspector)$('#inspector').hidden=false;const g={type:'Polygon',coordinates:[[a,[b[0],a[1]],b,[a[0],b[1]],a]]};if(Spatial.area(g)<1){toast('选区过小，请重新框选');return}runGeometryQuery(g,'框选范围相交查询');}else drawPreview();});
map.on('mousemove',e=>{$('#coords').textContent=`经度 ${e.latlng.lng.toFixed(4)}°　纬度 ${e.latlng.lat.toFixed(4)}°`});
map.on('zoomend',()=>{if(map.getZoom()>=7){if(!map.hasLayer(counties))counties.addTo(map)}else if(map.hasLayer(counties))map.removeLayer(counties)});
function updateClip(){const svg=map.getPane('business').querySelector('svg');if(!svg)return;const offset=map.getContainer().getBoundingClientRect().left+map.getSize().x*state.compare/100-svg.getBoundingClientRect().left;svg.style.clipPath=state.compare<100?`inset(0 0 0 ${Math.max(0,offset)}px)`:'';}
map.on('move zoom resize',updateClip);
function stopCompare(){state.compare=100;$('#compare-control')?.remove();updateClip();}
function showScene(id){const s=scenarios.find(s=>s.id===id)||scenarios[0];state.scene=s.id;setLayers(s.layers);$('#map-title').textContent=s.name;$('#map-subtitle').textContent=s.description;panel(s.name,s.en,`<p>${s.description}</p><h3>办理路径</h3>${s.steps.map((x,i)=>`<div class="flow-step"><b>${i+1}</b><span>${x}</span><small>${i===0?'从地图开始':''}</small></div>`).join('')}<h3>业务图层</h3><div class="chip-row">${s.layers.map(id=>`<button class="chip" data-action="resource" data-id="${id}">${byId[id].name}</button>`).join('')}</div><div class="field"><button class="secondary wide" data-action="scene-query">在当前区域查看业务对象</button><button class="secondary wide" data-action="draw-query">绘制范围并查询</button></div><p class="note">对应功能清单 ${s.requirement}。当前实现地图查询与核查任务主流程；专业评估、审批及外部系统接口见需求说明书。</p>`,`<button class="primary wide" data-action="task-new">创建场景核查任务</button>`,'scene');}
function updateAssistantContext(){const node=$('#assistant-context');if(node)node.textContent=[state.region||'全自治区',state.active.size+' 个图层',state.selected?'选中：'+state.selected.name:'未选中对象',state.drawGeometry?'已有绘制范围':''].filter(Boolean).join(' · ');}
function showAI(){state.assistantOpen=true;const dock=$('#assistant-dock');dock.hidden=false;dock.innerHTML=`<div class="inspector-header"><span class="eyebrow">YOUR SPATIAL COPILOT</span><h2>一张图助手</h2><button class="close-button" data-action="close-assistant" aria-label="收起智能助手">${icon('close')}</button></div><div id="assistant-context" class="assistant-context"></div><div class="assistant-conversation"><div class="chat-message"><small>空间协同 · 本地规则演示</small>我会结合你当前的区域、图层、选中对象与绘制范围，帮助查询、分析和办理。</div><div class="assistant-suggestions"><button data-prompt="分析当前范围">分析当前范围</button><button data-prompt="分析选中对象周边10公里">周边 10 公里</button><button data-prompt="叠加生态保护红线">叠加生态红线</button><button data-prompt="创建核查任务">创建核查任务</button></div><div id="chat-messages">${chatHTML()}</div></div><form id="chat-form" class="chat-composer"><textarea id="chat-input" aria-label="输入地图查询问题" placeholder="查询、叠加图层、分析范围，或继续办理…"></textarea><div><button type="button" class="text-button" data-action="clear-chat">新会话</button><span>本地规则 · 不作专业结论</span><button class="primary" type="submit">执行 ↗</button></div></form>`;updateAssistantContext();$('#chat-input').value=state.assistantDraft||'';$('#assistant-trigger').setAttribute('aria-expanded','true');}
function closeAI(){state.assistantDraft=$('#chat-input')?.value||'';state.assistantOpen=false;$('#assistant-dock').hidden=true;$('#assistant-trigger').setAttribute('aria-expanded','false');}
function chatHTML(){return state.messages.map(m=>`<div class="chat-message ${m.role}"><small>${m.role==='user'?'我的问题':'处理结果'}</small>${esc(m.text).replace(/\n/g,'<br>')}</div>`).join('')}
function matchAssistantLayers(q){const names=[...layers].sort((a,b)=>b.name.length-a.name.length);let matched=names.filter(l=>q.includes(l.name)||q.includes(l.name.replace(/分布|图斑|样点|斑块/g,'')));if(!matched.length){const aliases={永久基本农田:['primeFarmland'],基本农田:['primeFarmland'],生态保护红线:['ecoRedline'],生态红线:['ecoRedline'],耕地:['primeFarmland'],矿业权:['miningRight','exploreRight'],采矿权:['miningRight'],地灾:['geoHazard'],林地:['forest'],草原:['grassland'],建设用地:['construction']};for(const [word,ids] of Object.entries(aliases))if(q.includes(word)){matched=ids.map(id=>byId[id]);break}}return matched;}
function ask(q){q=q.trim();if(!q)return;state.assistantDraft='';state.messages.push({role:'user',text:q});let response='',after=null;
 if(/违法|合规|新增|趋势|最新|同比|历史/.test(q)){response='当前模拟数据不足以认定违法、合规或年度变化。可以先叠加管控图层、查询范围，再创建核查任务。';}
 else if(/(?:创建|新建|发起).*(?:核查|任务)/.test(q)){response='已准备核查任务表单，带入当前对象、区域、图层和绘制范围。请填写核查说明并保存；我不会直接代替你办结任务。';after=()=>createTask();}
 else if(/申请.*(?:数据|资源|图层)|申请当前/.test(q)){const l=byId[(state.route==='resources'?state.resource:state.selected?.layerId)||state.resource];if(l){response='已打开“'+l.name+'”的申请表。请确认用途、区域和使用期限后提交。';after=()=>requestResource(l.id)}else response='请先在资源中心选择一个图层，或在地图选中一个对象，再说“申请当前图层”。';}
 else if(/(?:打开|进入|切换).*(?:场景|大管家|矿业|耕地|规划|要素)/.test(q)){const s=scenarios.find(s=>q.includes(s.name)||q.includes(({steward:'大管家',planning:'规划',farmland:'耕地',elements:'要素',mining:'矿业'})[s.id]));if(s){response='已切换到“'+s.name+'”并加载相关图层。你可以继续查询、绘制范围或登记核查任务。';after=()=>{state.scene=s.id;if(state.route!=='scenes')location.hash='scenes';else showScene(s.id)}}else response='可打开资源大管家、国土空间规划、耕地保护、要素保障或矿业权场景。';}
 else if(/(?:打开|开始|进行).*(?:量算|测量)|测量面积|测量距离/.test(q)){const area=/面积/.test(q);response='已准备'+(area?'面积':'距离')+'量算。在地图连续选点，使用顶部“完成绘制”获得结果。助手会暂时收起，让出绘图空间。';after=()=>{openTool('measure');startDraw(area?'area':'distance');closeAI()};}
 else if(/周边/.test(q)){const m=q.match(/(?:周边)?\s*(-?[\d.]+)\s*(公里|千米|米)/),r=m?Number(m[1])*(m[2]==='米'?.001:1):10;if(!state.selected)response='请先点击一个地图对象，或在属性表选择对象。我会以该对象中心查询周边；当前没有选中对象。';else if(!Number.isFinite(r)||r<.1||r>300)response='请输入 0.1 至 300 公里的周边距离。';else {const g=Spatial.circle(Spatial.center(state.selected.geometry),r*1000);runGeometryQuery(g,'助手：周边 '+r+' 公里');state.aiRows=resultData();response='以“'+state.selected.name+'”的几何中心为起点，在当前可见图层中找到 '+state.aiRows.length+' 个与 '+r+' 公里缓冲范围相交的对象。\n结果已上图，可继续创建核查任务。点位中心不代表法定地块边界。';}}
 else if(/分析当前范围|查询当前范围|查询选区|分析选区/.test(q)){const geometry=state.drawGeometry;if(!geometry||geometry.type!=='Polygon'){response='当前没有可查询的多边形范围。已准备范围查询工具，点击地图绘制后完成。你也可以选择图层再来问我。';after=()=>openTool('query')}else {runGeometryQuery(geometry,'助手：当前绘制范围');state.aiRows=resultData();response='当前绘制范围与 '+state.aiRows.length+' 个可见对象相交，结果已同步地图和属性表。\n这是空间关系查询，不构成合规判断。';}}
 else if(/^(?:请)?(?:叠加|加载|显示|隐藏|移除|关闭)/.test(q)){const matched=matchAssistantLayers(q);if(!matched.length)response='没有找到相应图层。可以说“叠加永久基本农田”或“隐藏生态保护红线”。';else{const remove=/隐藏|移除|关闭/.test(q);matched.forEach(l=>remove?state.active.delete(l.id):state.active.add(l.id));state.resultRows=null;refreshMap();renderSidebar();response='已'+(remove?'隐藏':'叠加')+'：'+matched.map(l=>l.name).join('、')+'。当前视图位置保持，可继续做范围或周边分析。';}}
 else if(/按盟市统计/.test(q)&&state.aiRows){const counts={};state.aiRows.forEach(f=>counts[f.region]=(counts[f.region]||0)+1);response=`基于上次查询的 ${state.aiRows.length} 个对象，按盟市统计：\n`+Object.entries(counts).map(([n,v])=>`${n}：${v} 个`).join('\n');showResults(state.aiRows,'助手：按盟市统计');}
 else {const matched=matchAssistantLayers(q);const region=NMG_GEO.centers.features.map(f=>f.properties.name).find(n=>q.includes(n)||q.includes(n.replace(/市$|盟$/,'')));const year=q.match(/(20\d{2})年/),status=['审批中','已备案','待报批','已登记','未审批'].find(s=>q.includes(s));const amount=q.match(/(?:超过|大于)\s*([\d.]+)\s*(亩|公顷|平方公里)/);const followup=/只看|继续|其中/.test(q)&&state.aiRows;
 if(!matched.length&&!followup){response='可以查询“呼和浩特市的永久基本农田”，也可以说“叠加生态保护红线”“分析当前范围”“分析选中对象周边10公里”“创建核查任务”或“申请当前图层”。';}
 else {let rows=followup?[...state.aiRows]:matched.flatMap(l=>l.features);const targetRegion=region||state.region;if(targetRegion)rows=rows.filter(f=>f.region===targetRegion);if(region){state.region=region;$('#region').value=region}if(year)rows=rows.filter(f=>Number(f.properties.year)===Number(year[1]));if(status==='未审批')rows=rows.filter(f=>['待报批','审批中','未审批'].includes(f.properties.approval));else if(status)rows=rows.filter(f=>f.properties.approval===status);if(amount){const threshold=Number(amount[1])*({'亩':1,'公顷':15,'平方公里':1500}[amount[2]]);rows=rows.filter(f=>f.area!=null&&Number(f.area)*({'亩':1,'公顷':15,'平方公里':1500,'平方米':.0015}[f.unit]||0)>threshold)}state.aiRows=rows;matched.forEach(l=>state.active.add(l.id));refreshMap();renderSidebar();showResults(rows,'助手查询');if(rows.length)fitFeatures(rows);response=`找到 ${rows.length} 个模拟对象。\n范围：${targetRegion||'全自治区'}；图层：${matched.length?matched.map(l=>l.name).join('、'):'沿用上次结果'}${year?'；年度：'+year[1]:''}${status?'；状态：'+status:''}${amount?'；登记面积大于 '+amount[1]+amount[2]:''}。\n结果已同步到地图与属性表，原有图层继续保留。${status==='未审批'?'“未审批”演示口径为待报批、审批中或未审批。':''}`;}}
 state.messages.push({role:'assistant',text:response});showAI();$('#chat-messages')?.lastElementChild?.scrollIntoView({block:'nearest'});after?.();}
function modal(title,body,footer=''){const m=$('#modal');m.innerHTML=`<div class="modal-header"><h2 id="modal-title">${title}</h2><button class="close-button" data-action="modal-close" aria-label="关闭对话框">${icon('close')}</button></div><div class="modal-body">${body}</div>${footer?`<div class="modal-footer">${footer}</div>`:''}`;if(!m.open)m.showModal();}
function requestResource(id){const l=byId[id];modal('申请示例数据',`<form id="request-form"><input type="hidden" name="layer" value="${id}"><p><strong>${esc(l.name)}</strong></p><label class="field">申请用途<textarea name="purpose" required minlength="4" maxlength="500" placeholder="请填写具体用途（至少 4 个字）"></textarea></label><label class="field">行政区范围<select name="region"><option value="">全自治区</option>${NMG_GEO.centers.features.map(f=>`<option ${f.properties.name===state.region?'selected':''}>${f.properties.name}</option>`).join('')}</select></label><label class="field">使用期限<select name="days"><option value="7">7 天</option><option value="30">30 天</option><option value="90">90 天</option></select></label><p class="note">本地演示流程。提交后需切换“演示管理员”审核，审核通过可下载所选区域的示例 GeoJSON。</p></form>`,`<button class="secondary" data-action="modal-close">取消</button><button class="primary" type="submit" form="request-form">提交申请</button>`);}
function showRequests(admin=false){const pending=state.requests.filter(r=>r.status==='待审核').length;panel(admin?'使用申请审核':'我的资源申请',admin?'REQUEST REVIEW':'MY REQUESTS',`<div class="metric-line"><strong>${admin?pending:state.requests.length}</strong><small>${admin?'项待审核':'项申请记录'}</small></div>${admin&&state.role!=='admin'?'<div class="hint warning">当前为业务人员视图。切换为演示管理员后可执行本地审核。</div><button class="secondary wide" data-action="identity">切换演示身份</button>':''}${state.requests.length?state.requests.slice().reverse().map(r=>{const expired=r.status==='已通过'&&Date.now()>r.expires;return `<div class="link-row"><div><strong class="object-title">${esc(r.resourceName||byId[r.layer]?.name||r.layer)}</strong><small style="display:block;margin:4px 0">${esc(r.region||'全自治区')} · ${r.days} 天</small><span class="tag ${r.status==='待审核'?'amber':''}">${expired?'已到期':r.status}</span></div><button data-action="request-detail" data-id="${r.id}" data-admin="${admin}">查看 ›</button></div>`}).join(''):'<p class="empty-text">还没有申请。<br>前往资源中心选择图层后发起。</p>'}`,'','requests');}
function requestDetail(id,admin=false){const r=state.requests.find(x=>x.id===id);if(!r)return;const expired=r.status==='已通过'&&Date.now()>r.expires;modal('资源申请详情',`<dl class="properties"><div><dt>申请编号</dt><dd>${esc(r.id)}</dd></div><div><dt>数据资源</dt><dd>${esc(byId[r.layer].name)}</dd></div><div><dt>申请范围</dt><dd>${esc(r.region||'全自治区')}</dd></div><div><dt>申请用途</dt><dd>${esc(r.purpose)}</dd></div><div><dt>状态</dt><dd>${expired?'已到期':r.status}</dd></div><div><dt>申请时间</dt><dd>${esc(r.time)}</dd></div>${r.review?`<div><dt>审核意见</dt><dd>${esc(r.review)}</dd></div>`:''}${r.expires?`<div><dt>有效期至</dt><dd>${new Date(r.expires).toLocaleString('zh-CN')}</dd></div>`:''}</dl>${admin&&r.status==='待审核'&&state.role==='admin'?'<label class="field">审核意见（退回必填）<textarea id="review-comment" placeholder="请输入处理意见"></textarea></label>':''}`,admin&&r.status==='待审核'&&state.role==='admin'?`<button class="danger" data-action="reject-request" data-id="${id}">退回</button><button class="primary" data-action="approve-request" data-id="${id}">审核通过</button>`:r.status==='已通过'&&!expired?`<button class="primary" data-action="download-resource" data-id="${id}">下载示例 GeoJSON</button>`:r.status==='待审核'?`<button class="secondary" data-action="withdraw-request" data-id="${id}">撤回申请</button>`:'');}
function createTask(){const scene=scenarios.find(s=>s.id===state.scene);modal('创建空间核查任务',`<form id="task-form"><label class="field">任务名称<input name="title" required minlength="3" maxlength="80" value="${esc(state.selected?state.selected.name+'核查':scene.name+'范围核查')}"></label><label class="field">责任单位<input name="owner" required value="${esc(state.selected?.properties.owner||'自治区自然资源业务部门（演示）')}"></label><label class="field">核查说明<textarea name="description" required minlength="4" maxlength="1000" placeholder="说明需要核查的空间问题与处理要求"></textarea></label><div class="hint">关联对象：${esc(state.selected?.name||'当前地图范围')}<br>关联场景：${scene.name}<br>将保存当前区域、图层与视图，便于继续办理。</div></form>`,`<button class="secondary" data-action="modal-close">取消</button><button class="primary" type="submit" form="task-form">保存核查任务</button>`);}
function showTasks(){panel('空间核查任务','SPATIAL TASKS',`<div class="metric-line"><strong>${state.tasks.filter(t=>t.status!=='已办结').length}</strong><small>项待处理</small></div>${state.tasks.length?state.tasks.slice().reverse().map(t=>`<div class="link-row"><div><strong class="object-title">${esc(t.title)}</strong><small style="display:block">${esc(t.owner)}</small><span class="tag ${t.status==='待核查'?'amber':''}">${t.status}</span></div><button data-action="task-detail" data-id="${t.id}">办理 ›</button></div>`).join(''):'<p class="empty-text">还没有核查任务。<br>在地图选择对象，或进入业务场景创建。</p>'}`,`<button class="primary wide" data-action="task-new">新建核查任务</button>`,'tasks');}
function taskDetail(id){const t=state.tasks.find(t=>t.id===id);if(!t)return;state.currentTask=id;restoreView(t.view);if(t.geometry)showGeometry(t.geometry);if(t.feature){const f=allFeatures.find(f=>f.id===t.feature);if(f){state.selected=f;locateFeature(f)}}panel(esc(t.title),'TASK DETAIL',`<span class="tag">${t.status}</span><dl class="properties"><div><dt>任务编号</dt><dd>${esc(t.id)}</dd></div><div><dt>责任单位</dt><dd>${esc(t.owner)}</dd></div><div><dt>创建时间</dt><dd>${esc(t.time)}</dd></div><div><dt>核查说明</dt><dd>${esc(t.description)}</dd></div></dl><h3>办理记录</h3><ol class="timeline">${t.history.map(h=>`<li class="active">${esc(h.action)}<small>${esc(h.time)}${h.note?'<br>'+esc(h.note):''}</small></li>`).join('')}</ol>${t.status!=='已办结'?'<label class="field">处理意见<textarea id="task-note" placeholder="填写核查处理情况"></textarea></label>':''}`,t.status==='待核查'?`<button class="primary wide" data-action="task-progress" data-id="${id}">领取并开始核查</button>`:t.status==='核查中'?`<button class="primary wide" data-action="task-progress" data-id="${id}">记录结果并办结</button>`:`<button class="secondary wide" data-action="tasks">返回任务列表</button>`,'task');}
function captureView(){return {center:[map.getCenter().lat,map.getCenter().lng],zoom:map.getZoom(),layers:[...state.active],region:state.region,base:state.base};}
function restoreView(v){if(!v)return;state.active=new Set((v.layers||[]).filter(id=>byId[id]));state.region=v.region||'';$('#region').value=state.region;setBase(v.base||'terrain');refreshMap();renderSidebar();map.setView(v.center,v.zoom,{animate:false});}
function saveBookmark(){modal('保存当前地图视图',`<form id="bookmark-form"><label class="field">书签名称<input name="name" required minlength="2" maxlength="60" value="${esc(state.region||'内蒙古')}${state.route==='scenes'?' · '+scenarios.find(s=>s.id===state.scene).name:' · 专题视图'}"></label><p class="note">保存当前中心位置、缩放层级、行政区、底图和已选图层。</p></form>`,`<button class="primary" type="submit" form="bookmark-form">保存书签</button>`);}
function showBookmarks(){modal('视图与场景书签',`<div class="bookmarks-list">${state.bookmarks.length?state.bookmarks.map(b=>`<div class="link-row"><button data-action="restore-bookmark" data-id="${b.id}">${esc(b.name)}<small style="display:block">${b.view.layers.length} 个图层 · ${esc(b.view.region||'全自治区')}</small></button><button data-action="delete-bookmark" data-id="${b.id}" aria-label="删除书签 ${esc(b.name)}">${icon('trash')}</button></div>`).join(''):'<p class="empty-text">尚未保存视图。<br>将当前专题组合保存后可一键恢复。</p>'}</div>`,`<button class="primary" data-action="save-bookmark">保存当前视图</button>`);}
function showOperations(){panel('归集与发布','DATA PIPELINE',`<p>按阶段查看数据准备情况，把问题定位到地图。</p><div class="step-strip"><span class="done">登记</span> › <span>质检</span> › <span>编目</span> › <span>发布</span></div>${state.operations.length?state.operations.map(o=>`<div class="link-row"><div><strong class="object-title">${esc(o.name)}</strong><small style="display:block">${esc(byId[o.layer]?.name||o.layer)}</small><span class="tag">${o.status}</span></div><button data-action="operation-detail" data-id="${o.id}">处理 ›</button></div>`).join(''):'<p class="empty-text">还没有归集登记。<br>选择一个现有示例图层开始流程。</p>'}<p class="note">质检对当前示例对象检查名称、坐标范围与几何基本结构；发布登记保存在本地，不生成外部 OGC 服务。</p>`,`<button class="primary wide" data-action="operation-new">新建归集登记</button>`,'operations');}
function operationNew(){modal('新建归集登记',`<form id="operation-form"><label class="field">登记名称<input name="name" required minlength="3" maxlength="80" placeholder="例如：呼和浩特耕地专题更新"></label><label class="field">数据来源<select name="layer">${layers.map(l=>`<option value="${l.id}">${esc(l.name)} · 现有示例</option>`).join('')}</select></label><label class="field">数源单位<input name="owner" required placeholder="请输入演示数源单位"></label><p class="note">本轮使用已有本地示例数据演示归集流程，不连接生产库。</p></form>`,`<button class="primary" type="submit" form="operation-form">建立登记</button>`);}
function operationDetail(id){const o=state.operations.find(x=>x.id===id);if(!o)return;state.currentOperation=id;state.active.add(o.layer);refreshMap();renderSidebar();panel(esc(o.name),'PIPELINE DETAIL',`<span class="tag">${o.status}</span><dl class="properties"><div><dt>数源单位</dt><dd>${esc(o.owner)}</dd></div><div><dt>关联图层</dt><dd>${esc(byId[o.layer].name)}</dd></div><div><dt>登记时间</dt><dd>${esc(o.time)}</dd></div><div><dt>对象数量</dt><dd>${byId[o.layer].features.length}</dd></div></dl>${o.check?`<h3>基础质检结果</h3><div class="hint ${o.check.errors?'warning':''}">检查 ${o.check.total} 个对象<br>发现 ${o.check.errors} 项基础问题</div><p class="note">检查内容：名称非空、经纬度范围、线最少点数、面环闭合。未包含专业拓扑与业务规则质检。</p>`:''}${o.status==='待编目'?`<label class="field">资源中文名称<input id="catalog-name" value="${esc(o.catalogName||o.name)}" maxlength="80"></label><label class="field">主题分类<select id="catalog-theme">${groups.map(g=>`<option>${g[0]}</option>`).join('')}</select></label>`:''}${o.catalogName?`<h3>编目信息</h3><p>${esc(o.catalogName)}<br><small>${esc(o.theme)}</small></p>`:''}${o.status==='已发布'?'<div class="hint">已完成本地发布登记，可返回资源目录预览图层。</div>':''}`,`<button class="primary wide" data-action="operation-next" data-id="${id}" ${o.status==='已发布'?'disabled':''}>${({'待质检':'执行基础质检','质检未通过':'重新质检','待编目':'保存编目信息','待发布':'发布至本地演示目录','已发布':'已完成本地发布'})[o.status]}</button>`,'operation');}
function geometryError(g){if(!g||!Array.isArray(g.coordinates))return true;if(g.type==='MultiLineString'&&g.coordinates.some(r=>!Array.isArray(r)||r.length<2))return true;const p=Spatial.points(g);if(!p.length||p.some(p=>!Array.isArray(p)||!Number.isFinite(p[0])||!Number.isFinite(p[1])||Math.abs(p[0])>180||Math.abs(p[1])>90))return true;if(g.type==='LineString'&&p.length<2)return true;const polys=g.type==='Polygon'?[g.coordinates]:g.type==='MultiPolygon'?g.coordinates:[];return polys.some(poly=>!poly.length||poly.some(r=>r.length<4||r[0][0]!==r.at(-1)[0]||r[0][1]!==r.at(-1)[1]));}
function showIdentity(){modal('演示身份与使用说明',`<p>当前身份：<strong>${state.role==='admin'?'演示管理员':'业务人员'}</strong></p><div class="field"><button class="secondary" data-action="role-analyst">以业务人员查看</button><button class="secondary" data-action="role-admin">以演示管理员查看</button></div><p class="note">身份切换仅用于展示交互和本地审核流程，不属于真实登录、角色鉴权或单点登录。业务记录保存在当前浏览器，不在不同设备间同步。</p><div class="hint">本地行政区与业务数据复用已有 demo；业务要素为模拟示例。真实数据、法定边界、统一用户中心与生产业务接口尚未接入。</div><h3>完整业务模块</h3><p class="note">以下入口沿用原 oneMap，需要通过项目自带服务运行。</p><div class="field"><a class="secondary" href="../index.html#/admin/overview">打开完整后台管理 ↗</a><a class="secondary" href="../index.html#/front/app-center">打开应用构建中心 ↗</a><a class="secondary" href="../index.html#/front/intelligence">打开原智能中心 ↗</a></div>`);}
function showIntegrations(monitor=false){const names=['测绘地理信息时空大数据服务平台','全区不动产登记信息管理平台','地质灾害防治平台','地质调查监测管理系统','国土空间规划“一张图”实施监督信息系统','土地资源信息储备系统','耕地保护与监测监管信息系统','多级一体化电子政务平台','自然资源厅门户网站'];panel(monitor?'系统接入与监测说明':'已有系统集成','SYSTEM INTEGRATION',`<p class="note" style="margin-top:0">可研列出的接入系统。当前未配置经过确认的访问地址与认证接口。</p>${names.map((n,i)=>`<div class="link-row"><span>${n}<small style="display:block">${i===8?'访问入口':i===4||i===6?'入口 + 单点登录 + 待办':'入口 + 单点登录'}</small></span><span class="tag gray">待接入</span></div>`).join('')}<p class="note">国家节点与三级租户贯通、实时服务巡检、主机/数据库监控属于后续对接范围。当前不展示虚构的在线率或接口健康值。</p>`,'','integrations');}
function showLogs(){panel('本地操作记录','ACTIVITY LOG',state.logs.length?`<ol class="timeline">${state.logs.slice(-30).reverse().map(l=>`<li>${esc(l.action)}<small>${esc(l.time)} · ${esc(l.role)}</small></li>`).join('')}</ol>`:'<p class="empty-text">尚无业务操作记录。</p>',`<button class="secondary wide" data-action="export-logs">导出本地记录</button>`,'logs');}
function download(name,text,type='application/json'){const blob=new Blob([text],{type}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function setBase(base){state.base=base;relief.setOpacity(base==='terrain'?.88:0);$('#map').style.background=base==='terrain'?'#e5eadf':'#edf1e9';province.setStyle({fillColor:base==='terrain'?'#edf0de':'#e1ebde',fillOpacity:base==='terrain'?.05:.7});$$('[data-base]').forEach(b=>b.classList.toggle('active',b.dataset.base===base))}
function route(id){const requestedAI=id==='ai';if(!navs.some(n=>n[0]===id))id='map';state.route=id;cancelDraw();stopCompare();closePanel();state.showResults=false;renderResults();$('#map-title').textContent=id==='map'?'自然资源一张图':navs.find(n=>n[0]===id)[1];$('#map-subtitle').textContent='山水林田湖草沙，在一张图上协同。';renderNav();renderSidebar();if(innerWidth<681){$('#sidebar').classList.toggle('mobile-hidden',id==='map');}if(id==='resources')showResource(state.resource||'primeFarmland');if(id==='tools')openTool(state.tool||'query');if(id==='scenes')showScene(state.scene);if(id==='tasks')showTasks();if(id==='operations')showOperations();map.invalidateSize();if(requestedAI)showAI();updateAssistantContext();}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-route]');if(!b||b.disabled)return;const d=b.dataset;if(d.route){location.hash=d.route;return}if(d.tool){openTool(d.tool);return}if(d.scene){showScene(d.scene);if(innerWidth<681)$('#sidebar').classList.add('mobile-hidden');return}if(d.catalog){state.catalogTab=d.catalog;renderSidebar();return}if(d.group){state.grouping=d.group;renderSidebar();return}if(d.base){setBase(d.base);return}if(d.prompt){ask(d.prompt);return}const id=d.id,action=d.action;
 if(action==='close-assistant'){closeAI();return}if(action==='open-assistant'){showAI();return}if(action==='modal-close'){$('#modal').close();return}if(action==='close-panel'){closePanel();return}if(action==='show-results')showResults();if(action==='close-results'){state.showResults=false;renderResults()}if(action==='page-prev'){state.page--;renderResults()}if(action==='page-next'){state.page++;renderResults()}if(action==='fit-results')fitFeatures(resultData());
 if(action==='clear-layers')setLayers([]);if(action==='resource')showResource(id);if(action==='toggle-resource'){toggleLayer(id);showResource(id)}if(action==='preview-resource'){state.active.add(id);refreshMap();showResults(filteredLayer(byId[id]),byId[id].name);fitFeatures(filteredLayer(byId[id]));renderSidebar()}
 if(action==='select-feature')selectFeature(allFeatures.find(f=>f.id===id));if(action==='locate-feature')locateFeature(allFeatures.find(f=>f.id===id));if(action==='locate-selected')locateFeature(state.selected);
 if(action==='draw-query')startDraw('query');if(action==='draw-box')startDraw('box');if(action==='draw-distance')startDraw('distance');if(action==='draw-area')startDraw('area');if(action==='finish-draw')finishDraw();if(action==='undo-draw'){state.drawPoints.pop();drawPreview()}if(action==='cancel-draw'){cancelDraw();if(geoHighlight){map.removeLayer(geoHighlight);geoHighlight=null}if(state.inspector)$('#inspector').hidden=false}
 if(action==='buffer-start'){const radius=Number($('#buffer-distance').value);if(!Number.isFinite(radius)||radius<.1||radius>300){toast('请输入 0.1 至 300 公里的距离');return}if($('#buffer-source').value==='selected'&&state.selected){runGeometryQuery(Spatial.circle(Spatial.center(state.selected.geometry),radius*1000),'周边 '+radius+' 公里')}else{state.bufferRadius=radius;startDraw('buffer')}}
 if(action==='compare-stop'){stopCompare();toast('已结束卷帘对照')}if(action==='scene-query'){const s=scenarios.find(s=>s.id===state.scene);const rows=visibleFeatures();showResults(rows,s.name);fitFeatures(rows)}
 if(action==='clear-chat'){state.assistantDraft='';state.messages=[];state.aiRows=null;showAI()}
 if(action==='request-resource')requestResource(id);if(action==='requests')showRequests();if(action==='approvals')showRequests(true);if(action==='request-detail')requestDetail(id,d.admin==='true');
 if(['approve-request','reject-request','withdraw-request'].includes(action)){const r=state.requests.find(x=>x.id===id);if(!r||r.status!=='待审核')return;if(action!=='withdraw-request'&&state.role!=='admin'){toast('请切换为演示管理员');return}const comment=$('#review-comment')?.value.trim()||'';if(action==='reject-request'&&!comment){toast('请填写退回原因');return}r.status=action==='approve-request'?'已通过':action==='reject-request'?'已退回':'已撤回';r.review=comment;r.reviewTime=stamp();if(action==='approve-request')r.expires=Date.now()+r.days*86400000;log(r.id+' '+r.status);$('#modal').close();showRequests(state.role==='admin');toast('申请'+r.status);}
 if(action==='download-resource'){const r=state.requests.find(x=>x.id===id);if(!r||r.status!=='已通过'||Date.now()>r.expires){toast('申请尚未通过或已到期');return}const fs=byId[r.layer].features.filter(f=>!r.region||f.region===r.region);download(byId[r.layer].name+'-模拟数据.geojson',JSON.stringify({type:'FeatureCollection',notice:'模拟数据，仅用于原型交互演示',features:fs.map(geometryFeature)},null,2),'application/geo+json');log('下载 '+r.id+'，'+fs.length+' 个示例对象');}
 if(action==='task-new')createTask();if(action==='tasks')showTasks();if(action==='task-detail')taskDetail(id);if(action==='task-progress'){const t=state.tasks.find(x=>x.id===id),note=$('#task-note')?.value.trim()||'';if(!t||t.status==='已办结')return;if(t.status==='核查中'&&note.length<4){toast('请至少填写 4 个字的核查结果');return}t.status=t.status==='待核查'?'核查中':'已办结';t.history.push({action:t.status,time:stamp(),note});log(t.id+' '+t.status);taskDetail(id);toast('任务状态已更新');}
 if(action==='save-bookmark'||action==='saved-scene')saveBookmark();if(action==='bookmarks')showBookmarks();if(action==='restore-bookmark'){const b=state.bookmarks.find(x=>x.id===id);if(b){restoreView(b.view);$('#modal').close();toast('已恢复 '+b.name)}}if(action==='delete-bookmark'){state.bookmarks=state.bookmarks.filter(x=>x.id!==id);persist();showBookmarks()}
 if(action==='operations')showOperations();if(action==='operation-new')operationNew();if(action==='operation-detail')operationDetail(id);if(action==='operation-next'){const o=state.operations.find(x=>x.id===id);if(!o)return;if(['待质检','质检未通过'].includes(o.status)){const fs=byId[o.layer].features;o.check={total:fs.length,errors:fs.filter(f=>!f.name||geometryError(f.geometry)).length};o.status=o.check.errors?'质检未通过':'待编目';}else if(o.status==='待编目'){const name=$('#catalog-name').value.trim();if(!name){toast('请填写资源中文名称');return}o.catalogName=name;o.theme=$('#catalog-theme').value;o.status='待发布';}else if(o.status==='待发布'){o.status='已发布';}log(o.name+' · '+o.status);operationDetail(id);toast('当前阶段：'+o.status)}
 if(action==='identity')showIdentity();if(action==='role-admin'||action==='role-analyst'){state.role=action==='role-admin'?'admin':'analyst';persist();$('#modal').close();toast('已切换为'+(state.role==='admin'?'演示管理员':'业务人员'));if(state.inspector==='requests')showRequests(state.route==='operations')}
 if(action==='integrations')showIntegrations();if(action==='integration-monitor')showIntegrations(true);if(action==='logs')showLogs();if(action==='catalog-admin'){location.hash='resources'}
 if(action==='export-logs')download('本地操作记录.json',JSON.stringify(state.logs,null,2));if(action==='export-csv'){const rows=resultData().slice(state.page*20,(state.page+1)*20);const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const csv=[['编号','名称','图层','盟市','旗县','登记面积','单位','状态','数据性质'],...rows.map(f=>[f.id,f.name,f.layerName,f.region,f.county,f.area,f.unit,f.properties.approval,'模拟示例'])].map(r=>r.map(cell).join(',')).join('\r\n');download('查询结果-本页示例.csv','\uFEFF'+csv,'text/csv;charset=utf-8')}
});
document.addEventListener('input',e=>{if(e.target.id==='layer-search'){state.searchLayers=e.target.value;$('#layer-tree').innerHTML=treeHTML()}if(e.target.id==='resource-search'){state.searchLayers=e.target.value;$('#resource-list').innerHTML=resourceList()}if(e.target.dataset.opacity){state.opacity[e.target.dataset.opacity]=Number(e.target.value)/100;refreshMap()}if(e.target.id==='compare-range'){state.compare=Number(e.target.value);updateClip()}});
document.addEventListener('change',async e=>{if(e.target.dataset.layer)toggleLayer(e.target.dataset.layer);if(e.target.id==='region')selectRegion(e.target.value);if(e.target.id==='geojson-file'){const file=e.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw new Error('文件大于 5 MB');const parsed=JSON.parse(await file.text());const fc=parsed.type==='FeatureCollection'?parsed:parsed.type==='Feature'?{type:'FeatureCollection',features:[parsed]}:{type:'FeatureCollection',features:[{type:'Feature',geometry:parsed,properties:{}}]};if(!Array.isArray(fc.features)||fc.features.length===0||fc.features.length>1000)throw new Error('需要 1 至 1,000 个对象');for(const f of fc.features){if(!['Point','MultiPoint','LineString','MultiLineString','Polygon','MultiPolygon'].includes(f.geometry?.type)||geometryError(f.geometry))throw new Error('几何结构或经纬度范围不正确')}const layer=L.geoJSON(fc,{style:{color:'#8059a0',weight:2,fillOpacity:.2},pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:6,color:'#8059a0'})}).addTo(map);state.imports.push(layer);map.fitBounds(layer.getBounds(),{padding:[60,60],maxZoom:12});$('#import-result').innerHTML=`<div class="hint">已预览 ${fc.features.length} 个对象<br>${esc(file.name)}</div>`;}catch(error){$('#import-result').innerHTML=`<div class="hint warning">导入失败：${esc(error.message)}。请检查文件后重试。</div>`}}});
document.addEventListener('submit',e=>{e.preventDefault();const form=e.target;
 if(form.id==='global-search')search($('#search-input').value);
 if(form.id==='chat-form'){ask($('#chat-input').value)}
 if(form.id==='coordinate-form'){const lng=Number($('#coord-lng').value),lat=Number($('#coord-lat').value);if(!Number.isFinite(lng)||!Number.isFinite(lat)||Math.abs(lng)>180||Math.abs(lat)>85){toast('请输入有效经纬度');return}const x=6378137*lng*Math.PI/180,y=6378137*Math.log(Math.tan(Math.PI/4+lat*Math.PI/360));$('#coordinate-result').innerHTML=`Web Mercator<br>X：${x.toFixed(3)} m<br>Y：${y.toFixed(3)} m`;if(geoHighlight)map.removeLayer(geoHighlight);geoHighlight=L.circleMarker([lat,lng],{radius:7,color:'#164d3b',fillOpacity:.6}).addTo(map);map.setView([lat,lng],10,{animate:false})}
 if(form.id==='request-form'){const fd=new FormData(form);const purpose=String(fd.get('purpose')).trim();if(purpose.length<4){toast('请填写具体申请用途');return}const r={id:'REQ-'+Date.now().toString(36).toUpperCase(),layer:fd.get('layer'),region:fd.get('region'),purpose,days:Number(fd.get('days')),status:'待审核',time:stamp()};state.requests.push(r);log('提交数据申请 '+r.id);$('#modal').close();showRequests();toast('申请已提交，等待本地演示审核')}
 if(form.id==='task-form'){const fd=new FormData(form);if(String(fd.get('description')).trim().length<4){toast('请填写具体核查说明');return}const t={id:'TASK-'+Date.now().toString(36).toUpperCase(),title:String(fd.get('title')).trim(),owner:String(fd.get('owner')).trim(),description:String(fd.get('description')).trim(),feature:state.selected?.id||null,view:captureView(),geometry:state.drawGeometry,status:'待核查',time:stamp(),history:[{action:'创建核查任务',time:stamp()}]};state.tasks.push(t);log('创建核查任务 '+t.id);$('#modal').close();showTasks();toast('核查任务已保存')}
 if(form.id==='bookmark-form'){const name=String(new FormData(form).get('name')).trim();if(!name)return;state.bookmarks.push({id:'BM-'+Date.now(),name,view:captureView()});log('保存地图书签 '+name);$('#modal').close();toast('书签已保存')}
 if(form.id==='operation-form'){const fd=new FormData(form);const o={id:'OP-'+Date.now(),name:String(fd.get('name')).trim(),layer:fd.get('layer'),owner:String(fd.get('owner')).trim(),status:'待质检',time:stamp()};state.operations.push(o);log('创建归集登记 '+o.name);$('#modal').close();operationDetail(o.id)}
});
$('#assistant-trigger').innerHTML=icon('spark')+'<span>智能助手</span><kbd>⌥ A</kbd>';$('#assistant-trigger').onclick=()=>state.assistantOpen?closeAI():showAI();
$('#toggle-sidebar').innerHTML=icon('menu');$('#pin-icon').innerHTML=icon('pin');$('#search-icon').innerHTML=icon('search');$('#overview-toggle').innerHTML=icon('chart')+'区域概览';$('#reset-view').innerHTML=icon('extent')+'全区视图';
$('#map-tools').innerHTML=[['zoom-in','plus','放大'],['zoom-out','minus','缩小'],['divider','',''],['query','polygon','绘制范围查询'],['measure','measure','地图量算'],['buffer','circle','周边分析'],['compare','compare','图层卷帘对照'],['clear-map','trash','清除绘制与选中']].map(([id,i,label])=>id==='divider'?'<span class="tool-divider"></span>':`<button id="tool-${id}" aria-label="${label}" title="${label}">${icon(i)}</button>`).join('');
$('#tool-zoom-in').onclick=()=>map.zoomIn();$('#tool-zoom-out').onclick=()=>map.zoomOut();['query','measure','buffer','compare'].forEach(id=>$('#tool-'+id).onclick=()=>{state.tool=id;if(state.route!=='tools')location.hash='tools';else openTool(id)});
$('#tool-clear-map').onclick=()=>{cancelDraw();if(geoHighlight)map.removeLayer(geoHighlight);if(detailHighlight)map.removeLayer(detailHighlight);state.imports.forEach(l=>map.removeLayer(l));state.imports=[];geoHighlight=null;detailHighlight=null;state.selected=null;state.drawGeometry=null;state.resultRows=null;state.showResults=false;renderResults();stopCompare();updateAssistantContext();if(state.inspector==='feature')closePanel();toast('已清除绘制、导入图层与选中对象')};
$('#toggle-sidebar').onclick=()=>{if(innerWidth<681)$('#sidebar').classList.toggle('mobile-hidden');else $('#sidebar').classList.toggle('collapsed');map.invalidateSize()};
$('#overview-toggle').onclick=()=>state.inspector==='overview'?closePanel():showOverview();$('#reset-view').onclick=()=>selectRegion('');$('#results-toggle').onclick=()=>{state.showResults=!state.showResults;renderResults()};$('#bookmarks').onclick=showBookmarks;$('#identity').onclick=showIdentity;
NMG_GEO.centers.features.forEach(f=>{const o=document.createElement('option');o.value=f.properties.name;o.textContent=f.properties.name;$('#region').append(o)});
window.addEventListener('hashchange',()=>route(location.hash.slice(1)));window.addEventListener('keydown',e=>{if(e.altKey&&e.code==='KeyA'){e.preventDefault();state.assistantOpen?closeAI():showAI()}if(e.key==='Escape'){cancelDraw();if(state.inspector)$('#inspector').hidden=false}});let compactLayout=innerWidth<681;window.addEventListener('resize',()=>{if(innerWidth<681&&!compactLayout)$('#sidebar').classList.add('mobile-hidden');compactLayout=innerWidth<681;map.invalidateSize()});
const initial=location.hash.slice(1)||'map';route(initial);refreshMap();requestAnimationFrame(()=>{fitAll();const initialAsk=new URLSearchParams(location.search).get('ask');if(initialAsk)ask(initialAsk)});
