import {createResultsWorkspace} from './results-workspace.js?v=20260916-ai-map-r1';
import {createResultViews} from './integration-results.js?v=20260916-workspace-apps-r2';
import {integrationNav,settingsPath} from './integration-routes.js';
import {createIntegrationAdmin,integrationSections} from './integration-admin.js?v=20260916-results-round2-final';
import {loadImage} from './workspaces.js';
import {createIntegrationMap} from './integration-map.js?v=20260917-properties-1';

export function createIntegration(ctx){
  const {$,esc,btn,tag,api,modal,closeModal,toast,nav}=ctx;
  const D=()=>ctx.state().D,I=()=>{const raw=D().integration;return route==='integration-settings'?raw:{...raw,...raw.resourcePortal};};
  const params=()=>new URLSearchParams(location.hash.split('?')[1]);
  let workData=null,workKey='',workLoading=false,workBootstrap=null,workError='';
  const work=()=>workData||I().personalWorkbench;
  const usePath=(values={})=>'/admin/'+route+'?'+new URLSearchParams(values);
  function syncCatalog(){nav(usePath({...Object.fromEntries(params()),...(tab?{tab}:{}),query,kind,theme,department,page}));}

  let adminLocation='',carouselTimer=null,slide=0,carouselPaused=false,monitorFilters={start:'',end:'',period:'day',department:'',eventType:'all'},route='',tab='',query='',kind='全部',theme='',department='',page=1,monitorData=null,timer=null,generation=0;
  const adminTabs=integrationSections.map(([key,label])=>[key,label]);
  
  const B=(label,op,id='',style='small')=>btn(label,'ig-'+op,id,style);
  const field=(key,label,val='',type='text',choices=[])=>`<label class="ct-field"><span>${esc(label)}</span>${type==='select'||type==='multi'?`<select name="${key}" ${type==='multi'?'multiple size="5"':''}>${choices.map(o=>{const [k,n]=Array.isArray(o)?o:[o,o];return `<option value="${esc(k)}" ${(Array.isArray(val)?val:[String(val)]).includes(String(k))?'selected':''}>${esc(n)}</option>`}).join('')}</select>`:type==='check'?`<input type="checkbox" name="${key}" ${val?'checked':''}>`:type==='textarea'||type==='json'?`<textarea name="${key}" rows="4">${esc(typeof val==='object'?JSON.stringify(val,null,2):val)}</textarea>`:`<input name="${key}" type="${type}" ${type==='number'?'step="any"':''} value="${esc(val)}" ${key==='name'?'required maxlength="100"':''}>`}</label>`;
  const note=s=>`<p class="notice">${esc(s)}</p>`;
  const link=(label,path)=>`<a class="btn small" href="${esc(path)}">${esc(label)}</a>`;
  const table=(heads,rows)=>`<div class="table-scroll"><table><thead><tr>${heads.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${heads.length}">暂无记录</td></tr>`}</tbody></table></div>`;
  const tr=(...xs)=>`<tr>${xs.map(x=>`<td>${x??'—'}</td>`).join('')}</tr>`;
  const empty=s=>`<div class="empty">${esc(s)}</div>`;
  const tabs=rows=>`<div class="tabs ct-tabs">${rows.map(([k,n])=>B(n,'tab',k,tab===k?'active':'')).join('')}</div>`;
  function imageEditor(key,label,value=''){
    return field(key,label+' · HTTPS地址',value.startsWith('data:')?'':value)+`<label class="ct-field"><span>${esc(label)} · 上传PNG/JPEG/WebP</span><input type="file" accept="image/png,image/jpeg,image/webp" data-ig-upload="${key}"><small>图片压缩后保存；视频继续使用HTTPS地址。</small></label><div class="ct-full ig-image-editor"><input type="hidden" name="${key}Data" value="${esc(value.startsWith('data:')?value:'')}"><img data-ig-image="${key}" src="${esc(value||'')}" alt="素材预览" ${value?'':'hidden'}>${B('清除素材','clear-image',key)}</div>`;
  }
  function bindUploads(f){
    f.querySelectorAll('[data-ig-upload]').forEach(input=>input.onchange=async()=>{const file=input.files[0];if(!file)return;const b=f.querySelector('[type=submit]');b.disabled=true;try{const data=await loadImage(file);if(!f.isConnected)return;const key=input.dataset.igUpload;f.elements[key+'Data'].value=data;f.elements[key].value='';const img=f.querySelector('[data-ig-image="'+key+'"]');img.src=data;img.hidden=false;}catch(e){f.querySelector('.ct-error').textContent=e.message;}finally{b.disabled=false;}});
    for(const key of ['image','background'])f.elements[key]?.addEventListener('input',()=>{const hidden=f.elements[key+'Data'];if(hidden)hidden.value='';});
  }
  function form(title,fields,submit){
    modal(title,`<form id="ig-form"><div class="ct-form-grid">${fields}</div><p class="ct-error" role="alert"></p><div class="form-footer sticky"><button class="btn primary" type="submit">保存</button></div></form>`,true);
    bindUploads($('#ig-form'));
    $('#ig-form').onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('[type=submit]');b.disabled=true;const v=Object.fromEntries(new FormData(f));f.querySelectorAll('[type=checkbox]').forEach(x=>v[x.name]=x.checked);f.querySelectorAll('[type=number]').forEach(x=>v[x.name]=Number(x.value));f.querySelectorAll('select[multiple]').forEach(x=>v[x.name]=[...x.selectedOptions].map(x=>x.value));for(const key of ['image','background']){if(v[key+'Data'])v[key]=v[key+'Data'];delete v[key+'Data'];}try{await submit(v)}catch(e){f.querySelector('.ct-error').textContent=e.message}finally{b.disabled=false}};
  }
  async function send(op,p={}){const result=await api('integration.'+op,p);closeModal();await ctx.reload();toast(['导入失败','校验失败'].includes(result.status)?(result.error||'校验失败，请查看批次错误'):'已保存');return result;}
  function metricCards(values){if(!Object.keys(values).length)return '';return `<div class="ct-metrics">${Object.entries(values).map(([n,v])=>`<div class="panel ig-metric"><span>${esc(n)}</span><strong>${esc(v)}</strong></div>`).join('')}</div>`}
  function navigation(){return '';}
  function metricLinks(values,op){return `<div class="ct-metrics">${Object.entries(values).map(([name,value])=>`<button class="panel ig-metric" data-action="ig-${op}" data-id="${esc(name)}"><span>${esc(name)}</span><strong>${esc(value)}</strong></button>`).join('')}</div>`;}


  function settings(){const s=I().settings;return `<section class="panel ct-panel"><h2>门户基础设置</h2><p>${esc(s.title)} · ${esc(s.theme==='blue'?'蓝色':'绿色')}主题 · 发布版本 ${s.version}</p>${B('编辑草稿','settings')}${B('草稿预览','preview','settings:')}${B('历史版本','versions','settings:')}${B('发布基础设置','settings-publish')}${link('查看已发布门户','#/front/integrated-portal')}</section>`}
  const labels={banner:'Banner',nav:'主导航',secondary:'二级入口',advantage:'核心优势',promotion:'成果宣传',dynamic:'资源动态'};
  function publications(entity){return table(['内容','类型 / 人群','状态 / 发布版本','生效窗口','操作'],I()[entity].map(r=>tr(`<strong>${esc(r.name)}</strong>`,esc(labels[r.kind]||r.kind)+'<small>'+esc(r.audience)+'</small>',tag(r.status)+' v'+r.version,esc((r.startsAt||'立即')+' — '+(r.endsAt||'长期')),B('编辑','edit',entity+':'+r.id)+B('预览','preview',entity+':'+r.id)+B('历史版本','versions',entity+':'+r.id)+B('发布','publish',entity+':'+r.id)+B('停用','disable',entity+':'+r.id)+(!r.published?B('删除草稿','delete',entity+':'+r.id):''))));}
  function cards(rows){
    const favorites=D().centers.favorites;
    return `<div class="ct-cards">${rows.map(r=>`<article class="panel ct-card"><div>${tag(r.group)}<small>${esc(r.placement.theme||r.category)}</small></div><h3>${esc(r.name)}</h3><p>${esc(r.placement.department||r.source||'统一资源目录')}</p><small>${esc(r.placement.region||r.region||'')}${r.updated?' · 更新 '+esc(r.updated):''}${r.count?' · 热度 '+r.count:''}</small><div class="actions">${B('详情','resource-detail',r.id)}${B(({数据:'查看详情 / 申请',服务:'查看详情 / 使用',工具:'打开工具',知识:'阅读内容',智能体:'查看智能体',应用场景:'进入应用'})[r.group]||'查看详情','open',r.id)}${B(favorites.includes(r.id)?'取消收藏':'收藏','favorite',r.id)}${r.placement.manual?link('使用手册',r.placement.manual):''}${route==='integration-settings'&&tab==='placement'?B('展示分类','placement',r.id):''}</div></article>`).join('')||empty('暂无符合条件的资源')}</div>`;
  }
  function catalog(group='',favorites=false,showSearch=true){
    let rows=I().catalog.filter(r=>(!group||r.group===group)&&(!favorites||D().centers.favorites.includes(r.id))&&(kind==='全部'||r.group===kind)&&(!theme||r.placement.theme===theme)&&(!department||(r.placement.department||r.source)===department)&&(!query||JSON.stringify([r.name,r.category,r.placement,r.source]).toLowerCase().includes(query.toLowerCase())));
    if(favorites){const order=I().preferences.order;rows.sort((a,b)=>(order.includes(a.id)?order.indexOf(a.id):999)-(order.includes(b.id)?order.indexOf(b.id):999));}
    let html=showSearch?`<form id="ig-search" class="ct-search"><input name="query" aria-label="综合搜索" placeholder="搜索资源、服务、工具或应用" value="${esc(query)}"><button class="btn primary" type="submit">综合查询</button>${B('重置','reset')}</form>`:'';
    if(!favorites)html+=`<div class="ct-catalog-filters">${field('kind','资源类型',kind,'select',['全部','数据','服务','工具','知识','智能体','应用场景'])}${field('theme','场景主题',theme,'select',[['','全部主题'],...I().themes])}${field('department','提供部门',department,'select',[['','全部部门'],...[...new Set(I().catalog.map(r=>r.placement.department||r.source).filter(Boolean))]])}<span>${rows.length} 项可见资源</span></div>`;
    if(favorites){const groups=[...new Set(rows.map(r=>I().preferences.groups[r.id]||'未分组'))];html+=groups.map(g=>`<h2>${esc(g)}</h2>${cards(rows.filter(r=>(I().preferences.groups[r.id]||'未分组')===g))}`).join('')||empty('尚未收藏，请前往数字资源门户添加');}
    else html+=cards(rows.slice((page-1)*12,page*12))+`<div class="pagination"><span>第 ${page} / ${Math.max(1,Math.ceil(rows.length/12))} 页</span>${page>1?B('上一页','page',String(page-1)):''}${rows.length>page*12?B('下一页','page',String(page+1)):''}</div>`;
    return html;
  }
  function contentCard(r){return `<article class="panel ct-card ig-content ${r.kind==='banner'?'ig-banner':''}">${r.image?(r.media==='video'?`<video controls preload="none" src="${esc(r.image)}"></video>`:`<img loading="lazy" src="${esc(r.image)}" alt="${esc(r.name)}">`):''}<h3 ${r.kind==='banner'?`style="color:${esc(r.color)}"`:''}>${esc(r.symbol||'')} ${esc(r.name)}</h3><p>${esc(r.description)}</p>${r.url?link(r.button||'查看',r.url):''}</article>`}
  function home(){const rows=I().contents,m=I().metrics,searching=query||kind!=='全部'||theme||department||params().get('view')==='catalog';
    const shortcuts=rows.filter(r=>['nav','secondary'].includes(r.kind)).map(r=>{const admin=({'#/front/shared-resources':'center-resources','#/front/capabilities':'center-tools','#/front/app-center':'app-registry','#/front/intelligence':'agents'})[r.url];return admin&&ctx.canAdminRoute(admin)?{...r,url:'#/admin/'+admin}:r;}).filter(r=>!r.url.startsWith('#/admin/')||ctx.canAdminRoute(r.url.slice(8).split(/[/?]/)[0]));
    return `<section class="panel ct-panel ig-resource-search"><h2>查找所需资源</h2><form id="ig-search" class="ct-search"><input name="query" aria-label="综合搜索" placeholder="搜索数据、服务、工具、知识、智能体或应用" value="${esc(query)}"><button class="btn primary" type="submit">搜索</button>${B('重置','reset')}</form><div class="ig-hot"><span>热门搜索</span>${m.globalHotwords.map(r=>B(r.name,'hot',r.name)).join('')||'<small>暂无足够的聚合搜索记录</small>'}</div>${m.hotwords.length?`<details><summary>我的搜索历史</summary>${m.hotwords.map(r=>B(r.name,'hot',r.name)).join('')}</details>`:''}</section>${metricLinks(m.counts,'resource-kind')}<nav class="ig-nav" aria-label="中心快捷入口">${shortcuts.map(r=>link(r.name,r.url)).join('')}${I().tenants.length?link('本级租户资源','#/admin/integration-resources?view=tenants'):''}</nav>${params().get('view')==='tenants'?tenants():`${searching?`<section class="ig-section"><h2>搜索结果</h2>${catalog('',false,false)}</section>`:link('浏览全部资源','#/admin/integration-resources?view=catalog')}${!searching?`<section class="ig-section"><h2>最新资源</h2>${cards(I().catalog.slice().sort((a,b)=>(b.updated||'').localeCompare(a.updated||'')).slice(0,6))}</section><section class="ig-section"><h2>热门资源</h2><p class="muted">${esc(m.popularityScope)}</p>${cards(m.popular)}</section>`:''}`}${I().messages.some(m=>m.announcement)?`<section class="panel ct-panel"><h2>公告</h2>${I().messages.filter(m=>m.announcement).slice(0,4).map(m=>B(m.name,'message',m.id)).join('')}</section>`:''}${rows.some(r=>r.kind==='banner')?`<section class="ig-section ig-carousel"><h2>成果宣传</h2><div>${rows.filter(r=>r.kind==='banner').sort((a,b)=>a.order-b.order).map(r=>`<div data-ig-slide>${contentCard(r)}</div>`).join('')}</div><div class="actions">${B('上一张','slide-prev')}${B('下一张','slide-next')}${I().settings.bannerAutoplay?B(carouselPaused?'继续轮播':'暂停轮播','slide-pause'):''}<span id="ig-slide-count"></span></div></section>`:''}${['promotion','dynamic','advantage'].filter(k=>rows.some(r=>r.kind===k)).map(k=>`<section class="ig-section"><h2>${labels[k]}</h2><div class="ct-cards">${rows.filter(r=>r.kind===k).sort((a,b)=>a.order-b.order).map(contentCard).join('')}</div></section>`).join('')}`;
  }
  function tasks(limit=0){if(workError)return note('任务读取失败：'+workError)+B('重试','work-retry');const data=work(),rows=limit?data.todos.slice(0,limit):data.todos;return table(['任务 / 来源','状态','发起 / 截止时间','办理'],rows.map(r=>tr(`<strong>${esc(r.name)}</strong><small>${esc(r.source)}</small>`,tag(r.status)+' '+tag(r.timeliness),esc(r.createdAt||'来源未提供')+'<small>'+esc(r.dueAt||'未设期限')+'</small>',r.entry?`<a class="btn small" data-ig-return href="${esc(r.entry)}">进入办理</a>`:'来源系统尚未配置办理入口')));}
  function messageTable(limit=0){let rows=I().messages.filter(m=>(params().get('unread')!=='1'||!m.read)&&(!params().get('messageKind')||m.kind===params().get('messageKind')));if(limit)rows=rows.slice(0,limit);return table(['消息','分类','时间','状态','操作'],rows.map(r=>tr(esc(r.name),esc(r.kind),esc(r.at),tag(r.read?'已读':'未读'),B('查看','message',r.id))));}
  function favoriteSection(group){const p=I().preferences;let rows=I().catalog.filter(r=>r.group===group&&I().personalWorkbench.favorites.includes(r.id));rows.sort((a,b)=>(p.order.includes(a.id)?p.order.indexOf(a.id):999)-(p.order.includes(b.id)?p.order.indexOf(b.id):999));return [...new Set(rows.map(r=>p.groups[r.id]||'常用'))].map(g=>`<h3>${esc(g)}</h3>${cards(rows.filter(r=>(p.groups[r.id]||'常用')===g))}`).join('')||empty('暂无收藏，前往数字资源添加');}
  function desk(){const view=params().get('view')||({apps:'apps',tools:'tools',messages:'messages',tenants:'tenants'})[params().get('tab')]||'',values={...I().personalWorkbench.counts,消息:I().messages.filter(r=>!r.read).length,收藏:I().personalWorkbench.favorites.length};
    const top=`<div class="actions">${view?link('返回工作桌面','#/admin/integration-workbench'):''}${B('个人设置','preferences')}${link('查找资源','#/admin/integration-resources')}</div>${metricLinks(Object.fromEntries(I().preferences.metrics.filter(k=>Object.hasOwn(values,k)).map(k=>[k,values[k]])),'work-filter')}${metricCards(Object.fromEntries(I().dashboard.filter(r=>I().preferences.metrics.includes(r.id)).map(r=>[r.name+'（'+r.unit+'）',r.value])))}`;
    if(view==='tasks')return top+`<section class="panel ct-panel"><h2>我的待办 · ${work().todos.length}</h2><form id="ig-task-filter" class="ig-admin-filter">${field('query','任务名称',params().get('query')||'')}${field('status','办理 / 时效状态',params().get('status')||'全部','select',['全部','待办','正常','逾期','预警','已办'])}${field('source','来源系统',params().get('source')||'','select',[['','全部来源'],...work().sources])}<button class="btn primary" type="submit">筛选</button></form>${workLoading?'<p role="status">正在读取本人任务…</p>':tasks()}</section>`;
    if(view==='messages')return top+`<section class="panel ct-panel"><h2>我的消息</h2><form id="ig-message-filter" class="ig-admin-filter">${field('unread','阅读状态',params().get('unread')||'','select',[['','全部'],['1','未读']])}${field('messageKind','消息类型',params().get('messageKind')||'','select',[['','全部'],...new Set(I().messages.map(m=>m.kind))])}<button class="btn primary">筛选</button></form>${messageTable()}</section>`;
    if(view==='favorites')return top+catalog('',true);
    if(view==='apps'||view==='tools')return top+favoriteSection(view==='apps'?'应用场景':'工具');
    if(view==='tenants')return top+tenants();
    return top+`<div class="ig-desk-grid"><section class="panel ct-panel"><div class="ig-section-heading"><h2>我的待办</h2>${link('查看全部','#/admin/integration-workbench?view=tasks&status=全部')}</div><p class="muted">仅本人任务；外部任务在来源系统办理，状态以再次同步为准。</p>${workLoading?'<p role="status">正在读取本人待办…</p>':tasks(8)}${link('本地业务办理','#/front/workbench')}${link('我的交付与订阅','#/front/shared-resources')}</section><aside><section class="panel ct-panel"><div class="ig-section-heading"><h2>我的应用</h2>${link('查看全部','#/admin/integration-workbench?view=apps')}</div>${favoriteSection('应用场景')}</section><section class="panel ct-panel"><div class="ig-section-heading"><h2>我的工具</h2>${link('查看全部','#/admin/integration-workbench?view=tools')}</div>${favoriteSection('工具')}</section></aside></div><section class="panel ct-panel"><div class="ig-section-heading"><h2>消息提醒与公告</h2>${link('全部消息','#/admin/integration-workbench?view=messages')}</div><p class="muted">${I().quiet?'免打扰时段，弹窗静默':I().preferences.notify?'通知已开启':'通知提示已关闭'}</p>${messageTable(5)}</section>`;
  }
  function tenants(){return note('此处为独立租户工作空间，成员、资源记录及分级授权在服务端隔离；尚未对现有全平台模块实施租户化。')+table(['租户 / 层级','上级 / 区域','开放权限','操作'],I().tenants.map(t=>tr(`<strong>${esc(t.name)}</strong><small>${esc(t.level)}</small>`,esc(I().tenants.find(x=>x.id===t.parentId)?.name||'无')+'<small>'+esc(t.region)+'</small>',esc(t.permissions.join(' / ')),(I().permissions[t.id]?.includes('children')?B('编辑','tenant-edit',t.id)+(t.level!=='旗县'?B('创建下级','tenant-child',t.id):''):'')+(I().permissions[t.id]?.includes('members')?B('成员权限','tenant-member',t.id):'')+(I().permissions[t.id]?.includes('write')?B('新增空间资源','tenant-asset',t.id):''))))+`<h2>空间资源</h2>`+table(['名称','所属租户','说明','操作'],I().tenantAssets.map(r=>tr(esc(r.name),esc(I().tenants.find(t=>t.id===r.tenantId)?.name),esc(r.description),r.url?link('访问',r.url):'—')))+`<h2>可管理成员</h2>`+table(['用户','租户','权限'],I().members.map(m=>tr(esc(D().accounts.find(u=>u.id===m.userId)?.name||m.userId),esc(I().tenants.find(t=>t.id===m.tenantId)?.name),esc(m.permissions.join(' / ')||'已收回'))));}
  function peers(kind){const rows=I().peers.filter(r=>r.kind===kind);return note(({国家对接:'国家节点：登记统一命名与域名，联调国家用户体系、基础服务和省级服务注册。',纵向交换:'纵向节点：维护自治区、盟市、旗县的层级关系，交换目录与服务并关联本级资源空间。',横向联动:'横向平台：明确对接单位、用户互认和共享服务范围。'})[kind]+' 配置检查和文件交换仅在本地执行，真实认证与网络传输待接口联调。')+B('新增接入对象','peer-edit','', 'primary')+table(['接入对象','方向 / 状态','端点 / 认证','操作'],rows.map(r=>tr(esc(r.name),esc(r.direction)+' '+tag(r.status),esc(r.endpoint||'未配置')+'<small>'+esc(r.authClientId||'无认证客户端')+'</small>',B('配置','peer-edit',r.id)+link('实施进展','#'+settingsPath('plans',{system:r.id}))+(['导入','双向'].includes(r.direction)?B('导入交换清单','exchange-import',r.id):'')+(['导出','双向'].includes(r.direction)?B('导出目录','exchange-export',r.id):''))))+`<h2>已接收目录</h2>`+table(['资源','来源标识','类型','版本'],(I().received||[]).filter(r=>rows.some(p=>p.id===r.peerId)).map(r=>tr(esc(r.name),esc(r.externalId),esc(r.kind),r.rev)))+`<h2>交换记录</h2>`+table(['对象 / 时间','方向','结果','条数','说明'],I().exchanges.filter(r=>rows.some(p=>p.id===r.peerId)).slice().reverse().map(r=>tr(esc(r.name)+'<small>'+esc(r.at)+'</small>',esc(r.direction),tag(r.status),r.count,esc(r.error||'本地交换，不代表外部联通')+B('查看条目','exchange-detail',r.id))));}
  function systems(){const filter=new URLSearchParams(location.hash.split('?')[1]).get('filter');const issues=I().administration.systemIssues;let rows=D().centers.systems;if(filter==='incomplete')rows=rows.filter(r=>issues.some(x=>x.id===r.id));return `<div class="actions">${link('全部系统','#/admin/center-integration?tab=systems')}${link('待完善配置','#/admin/center-integration?tab=systems&filter=incomplete')}</div>`+table(['系统','接入能力','配置状态 / 负责人','操作'],rows.map(r=>tr(`<strong>${esc(r.name)}</strong><small>${esc(r.entry||'未配置入口')}</small>`,esc('入口'+(r.requiresSso?' · 单点登录':'')+(r.todoEnabled?' · 待办':'')),tag(r.status)+'<small>'+esc(r.contact||'未指定负责人')+'</small>',B('接入详情','system-detail',r.id)+btn('编辑配置','ct-edit','systems:'+r.id,'small')+(r.todoEnabled?link('待办同步','#/admin/center-integration?tab=tasks&system='+encodeURIComponent(r.id)):''))));}

  function bars(rows){const max=Math.max(1,...rows.map(r=>r.count));return rows.length?`<div class="ig-bars">${rows.map(r=>`<div><span>${esc(r.name)}</span><i style="width:${r.count/max*100}%"></i><b>${r.count}</b></div>`).join('')}</div>`:empty('暂无实际事件');}
  function monitor(){const filter=`<form id="ig-monitor-filter" class="ig-monitor-filter">${field('start','开始日期',monitorFilters.start,'date')}${field('end','结束日期',monitorFilters.end,'date')}${field('period','趋势粒度',monitorFilters.period,'select',[['day','日'],['week','周'],['month','月']])}${field('eventType','事件结果',monitorFilters.eventType,'select',[['all','全部事件'],['success','工具成功'],['failure','工具失败'],['entry','入口打开']])}${field('department','调用部门',monitorFilters.department,'select',[['','全部部门'],...new Set(D().accounts.map(u=>u.department)),['历史事件未记录部门','历史事件未记录部门']])}<button class="btn primary" type="submit">统计查询</button></form>`;if(!monitorData)return filter+`<p>正在读取实际统计…</p>`;const m=monitorData;return filter+note(m.scope)+metricCards({'筛选期入口访问':m.opens,'访问用户':m.users,'工具成功':m.toolSuccess,'工具失败':m.toolFailed,'外部工具入口打开':m.externalOpens,'工具使用人数':m.toolUsers})+`<p>数据总容量：未采集 · 当前监测不代表外部服务健康检查</p>`+B('检查集成依赖','inspect','','primary')+`<div class="ig-columns">${[['资源访问排行',m.resourceRanks],['工具事件排行',m.toolRanks],['工具使用部门',m.departmentRanks],['来源部门资源数',m.providers],['八类场景编排数量',m.themes],['入口访问趋势',m.days],['工具事件趋势',m.toolTrend]].map(([n,r])=>`<section class="panel ct-panel"><h2>${n}</h2>${bars(r)}</section>`).join('')}</div><h2>依赖检查记录</h2>${table(['时间','范围','异常'],m.checks.slice().reverse().map(r=>tr(esc(r.at),esc(r.scope),r.failures.map(f=>`<p>${esc(f.name)}：${esc(f.reason)}</p>`).join('')||'未发现本地配置问题')))}`;}
  const adminUI=createIntegrationAdmin({...ctx,field,form,B,table,tr,tag,link,note,send});
  function admin(){const detail=systemDetail();if(detail!==null)return adminUI.sectionNav(tab)+detail;const workflow=adminUI.render(tab);if(workflow!==null)return adminUI.sectionNav(tab)+workflow;let content='';

    if(tab==='presentation')content=(new URLSearchParams(location.hash.split('?')[1]).get('filter')==='draft'?adminUI.draftQueue():'')+settings()+B('新增展示内容','edit','contents:','primary')+publications('contents');
    if(tab==='announcements')content=B('新建公告','edit','announcements:','primary')+publications('announcements');
    if(tab==='placement')content=note('复用原中心主记录，维护图层目录、展示归类及系统关联；目录登记不等于外部接入成功。')+resultUI.management();
    if(tab==='monitor')content=monitor();
    if(tab==='systems')content=systems();
    if(tab==='national')content=note('国家节点命名为“一张图”，省级为“一张图·省级行政区”。域名登记不等同DNS分配生效，国家SDK与服务注册协议仍待联调。')+peers('国家对接');
    if(tab==='horizontal')content=peers('横向联动');
    if(tab==='vertical')content=`<h2>纵向节点</h2>${btn('新增节点','ct-edit','nodes:','primary')}`+table(['节点','级别 / 方向','操作'],D().centers.nodes.map(r=>tr(esc(r.name),esc(r.level+' / '+r.direction),btn('配置','ct-edit','nodes:'+r.id,'small')+btn('导出目录','ct-export-node',r.id,'small'))))+`<h2>纵向交换适配</h2>`+peers('纵向交换');
    if(tab==='policy')content=`<section class="panel ct-panel"><h2>查询范围策略</h2><p>已发布上限：${esc(I().settings.published.maxAreaHa)} 公顷</p>${B('编辑范围策略','policy')}${B('发布范围策略','policy-publish')}</section>`;
    if(tab==='tenants')content=tenants();
    return adminUI.sectionNav(tab)+content;
  }
  function systemDetail(){const id=params().get('system');if(!id||!['systems','auth','tasks','receipts','plans'].includes(tab))return null;const r=D().centers.systems.find(r=>r.id===id)||I().peers.find(r=>r.id===id);if(!r)return empty('来源系统不存在');if(r.kind)return `<section class="panel ct-panel">${link('返回接入对象','#'+settingsPath(({国家对接:'national',纵向交换:'vertical',横向联动:'horizontal'})[r.kind]))}<h2>${esc(r.name)} · 实施进展</h2><p>${esc(r.kind)} · ${esc(r.contact||'未指定负责人')} · ${esc(r.status)}</p>${adminUI.render('plans')}</section>`;const links=[['systems','基本信息'],['auth','认证关联'],...(r.todoEnabled?[['tasks','待办接入'],['receipts','运行记录']]:[]),['plans','实施进展']];return `<section class="panel ct-panel">${link('返回接入系统','#'+settingsPath('systems'))}<h2>${esc(r.name)}</h2><p>${esc(r.contact||'未指定负责人')} · ${esc(r.status)}</p><nav class="ig-section-nav">${links.map(([key,label])=>`<a href="#${settingsPath(key,{system:id})}" ${tab===key?'aria-current="page"':''}>${label}</a>`).join('')}</nav>${tab==='systems'?`<dl class="ig-detail"><dt>访问入口</dt><dd>${esc(r.entry||'未配置')}</dd><dt>接入能力</dt><dd>系统入口${r.requiresSso?'、单点登录':''}${r.todoEnabled?'、待办':''}</dd><dt>配置问题</dt><dd>${esc(I().administration.systemIssues.find(x=>x.id===id)?.reason||'必填配置完整')}</dd></dl>${btn('编辑系统配置','ct-edit','systems:'+id,'small')}${btn('检查配置','ct-check-system',id,'small')}`:tab==='auth'?`<p>关联客户端：${esc(D().platform.authClients.find(c=>c.id===r.authClientId)?.name||'未绑定')}</p>${link('统一登录接入','#/admin/auth-clients')}${link('消息总线','#/admin/message-bus')}`:adminUI.render(tab)}</section>`;}
  const resultUI=createResultViews({...ctx,field,form,B,table,tr,tag,link,send,render});
  const mapUI=createIntegrationMap({...ctx,field,form,B,table,tr,tag,onChange:s=>workspaceUI.refresh(s)});
  const workspaceUI=createResultsWorkspace({...ctx,mapUI,resultUI});
  function results(){return workspaceUI.html(tab);}
  function render(){clearTimeout(timer);clearInterval(carouselTimer);carouselTimer=null;const state=ctx.state();if(!['integration-settings','integration-resources','internal-home','integration-workbench','integration-results'].includes(state.route)){workspaceUI.destroy();mapUI.destroy();return false;}if(!I())return false;
    generation++;workspaceUI.destroy();mapUI.destroy();
    if(route!==state.route){route=state.route;tab=route==='integration-settings'?'presentation':route==='integration-workbench'?'tasks':route==='integration-results'?'map':'';query='';kind='全部';theme='';department='';page=1;monitorData=null;}
    const isAdmin=state.mode==='admin',isManagement=route==='integration-settings';if(isManagement){const requested=new URLSearchParams(location.hash.split('?')[1]).get('tab')||'presentation';tab=[...adminTabs.map(x=>x[0]),'policy','auth'].includes(requested)?requested:'presentation';if(adminLocation!==location.hash){adminLocation=location.hash;query='';kind='全部';theme='';department='';page=1;monitorData=null;const resourceKind=new URLSearchParams(location.hash.split('?')[1]).get('filter');if(tab==='placement'&&['数据','服务','工具','知识','智能体','应用场景'].includes(resourceKind))kind=resourceKind;}}if(isAdmin&&!(isManagement?I().canManage:route==='integration-results'?I().resultPermissions?.view:I().internalAccess)){$('#main').innerHTML=empty('当前身份没有此工作空间的访问权限');return true;}
    if(!isManagement||tab==='placement'){const p=params();if(!isManagement)tab=p.get('tab')||(route==='integration-results'?'map':'');query=p.get('query')||'';kind=p.get('kind')||(isManagement?p.get('filter'):null)||'全部';theme=p.get('theme')||'';department=p.get('department')||'';page=Math.max(1,Number(p.get('page'))||1);}
    if(route==='integration-workbench'){
      const f={status:params().get('status')||(params().get('view')==='tasks'?'全部':I().preferences.todoStatus==='全部'?'待办':I().preferences.todoStatus),source:params().get('source')||'',query:params().get('query')||''};
      const key=D().user.id+JSON.stringify(f)+D().serverTime;
      if(workKey!==key||workBootstrap!==D()){workKey=key;workBootstrap=D();workData=null;workLoading=true;workError='';const snapshot=D();api('integration.workbench',f).then(r=>{if(workKey!==key||snapshot!==D())return;workData=r;workLoading=false;if(ctx.state().route==='integration-workbench')render();}).catch(e=>{if(workKey===key&&snapshot===D()){workLoading=false;workError=e.message;render();}});}
    }
    const name=integrationNav.find(n=>n[0]===route)?.[1]||'';
    $('#main').innerHTML=`<div class="ct-workspace ig-workspace ${isAdmin?'':'portal-container'} ${route==='integration-results'?'mw-page':''}">${name&&route!=='integration-results'?`<div class="page-heading"><div><div class="eyebrow">ONE MAP · INTEGRATION</div><h1>${name}</h1><p>${({ 'integration-results':'浏览授权图层，使用工具和业务场景', 'integration-resources':'统一查找数据、服务、工具、知识、智能体与应用', 'integration-workbench':'处理本人待办，打开常用应用与工具', 'integration-settings':'维护门户展示、系统接入、运行与权限'})[route]||''}</p></div></div>`:''}${isManagement?admin():route==='integration-workbench'?desk():route==='integration-results'?results():home()}</div>`;
    if(isManagement)adminUI.bind(tab);
    if(route==='integration-results')resultUI.bind(tab);
    for(const [id,view] of [['ig-task-filter','tasks'],['ig-message-filter','messages']]){const f=$('#'+id);if(f)f.onsubmit=e=>{e.preventDefault();nav(usePath({view,...Object.fromEntries(new FormData(f))}));};}
    document.querySelectorAll('[data-ig-return]').forEach(a=>a.addEventListener('click',()=>sessionStorage.setItem('ig-return-'+D().user.id,location.hash)));

    $('#ig-search')?.addEventListener('submit',async e=>{e.preventDefault();query=new FormData(e.target).get('query').trim();page=1;try{await api('integration.search',{query});syncCatalog()}catch(e){toast(e.message)}});
    for(const name of ['kind','theme','department'])document.querySelector(`.ct-catalog-filters [name=${name}]`)?.addEventListener('change',e=>{if(name==='kind')kind=e.target.value;if(name==='theme')theme=e.target.value;if(name==='department')department=e.target.value;page=1;syncCatalog()});
    if(isAdmin&&tab==='monitor'&&!monitorData){const g=generation;api('integration.monitor',monitorFilters).then(r=>{if(g!==generation)return;monitorData=r;render()}).catch(e=>toast(e.message));}
    if(['integration-resources','internal-home'].includes(route))setupCarousel();
    const mf=$('#ig-monitor-filter');if(mf)mf.onsubmit=e=>{e.preventDefault();monitorFilters=Object.fromEntries(new FormData(mf));monitorData=null;render();};
    if(route==='integration-results')workspaceUI.bind().catch(e=>toast(e.message));

    if(route==='integration-workbench'){timer=setTimeout(()=>{if(!document.hidden&&!$('#dialog')?.open)ctx.reload();else renderRefresh()},I().preferences.refreshSeconds*1000);}
    if(!isManagement&&I().preferences.notify&&!I().quiet){const next=I().messages.find(m=>((m.announcement&&I().preferences.popup)||(m.task&&I().preferences.taskPopup))&&m.popup&&!m.read&&!sessionStorage.getItem('ig-seen-'+D().user.id+'-'+m.id));if(next&&!$('#dialog')?.open){sessionStorage.setItem('ig-seen-'+D().user.id+'-'+next.id,'1');showMessage(next);}}
    return true;
  }
  function updateSlide(){const slides=[...document.querySelectorAll('[data-ig-slide]')];if(!slides.length)return;slide=(slide+slides.length)%slides.length;slides.forEach((el,i)=>el.hidden=i!==slide);$('#ig-slide-count').textContent=(slide+1)+' / '+slides.length;}
  function setupCarousel(){updateSlide();const settings=I().settings;if(!settings.bannerAutoplay||matchMedia('(prefers-reduced-motion: reduce)').matches)return;carouselTimer=setInterval(()=>{const host=document.querySelector('.ig-carousel');if(carouselPaused||document.hidden||!host||host.matches(':hover')||host.contains(document.activeElement))return;slide++;updateSlide();},(settings.bannerSeconds||6)*1000);}
  function renderRefresh(){timer=setTimeout(()=>{if(!$('#dialog')?.open&&!document.hidden)ctx.reload();else renderRefresh()},I().preferences.refreshSeconds*1000);}
  function showMessage(m){modal(m.name,`<div class="ig-message ${m.style==='重点'?'ig-important':''}"><p>${esc(m.body).replaceAll('\n','<br>')}</p><small>${esc(m.at)} · ${esc(m.kind)}</small><div class="actions">${B(m.read?'已读':'标记已读','read',m.id)}${m.target?link('查看关联内容',m.target.startsWith('/')?'#'+m.target:m.target):''}</div></div>`);}
  function editor(entity,id){const r=I()[entity].find(x=>x.id===id)||{};let html=field('name','标题',r.name)+field('audience','目标人群',r.audience||'全部','select',['全部',...new Set(D().accounts.map(u=>u.role))])+field('startsAt','开始时间',r.startsAt,'datetime-local')+field('endsAt','结束时间',r.endsAt,'datetime-local')+field('url','链接地址（HTTPS或本站入口）',r.url);
    if(entity==='contents')html+=field('kind','展示区域',r.kind||'banner','select',Object.entries(labels))+field('description','简介 / 副标题',r.description,'textarea')+field('symbol','展示图标（符号或短文字）',r.symbol||'')+imageEditor('image','图片或视频',r.image||'')+field('media','媒体类型',r.media||'image','select',[['image','图片'],['video','视频']])+field('button','按钮文字',r.button||'查看')+field('color','Banner标题颜色',r.color||'#ffffff','color')+field('order','排序',r.order||0,'number');
    else html+=field('body','公告正文（包含数据/功能更新概述）',r.body,'textarea')+field('kind','公告类型',r.kind||'门户更新','select',['门户更新','数据上新','功能更新','系统通知'])+field('popup','弹窗提醒',r.popup??true,'check')+field('style','弹窗样式',r.style||'普通','select',['普通','重点']);
    html+=note('目标条件取交集；部门与租户不选择表示不限制。租户范围只投递给拥有该空间读取权限的成员。')+field('departments','目标部门',r.departments||[],'multi',[...new Set(D().accounts.map(u=>u.department))])+field('tenantIds','目标租户',r.tenantIds||[],'multi',I().tenants.map(t=>[t.id,t.name]));
    form(id?'编辑草稿':'新建内容',html,v=>send('save',{entity,id,rev:r.rev,values:v}));
  }
  function showPreview(r,entity,key,rev){const v=r.draft;const body=entity==='contents'?contentCard(v):entity==='announcements'?`<div class="ig-message ${v.style==='重点'?'ig-important':''}"><h2>${esc(v.name)}</h2><p>${esc(v.body).replaceAll('\n','<br>')}</p></div>`:`<section class="ig-hero ${v.theme==='blue'?'ig-blue':''}">${v.background?`<img class="ig-backdrop" src="${esc(v.background)}" alt="">`:''}<h1>${esc(v.title)}</h1><p>${esc(v.subtitle)}</p></section>`;
    modal('草稿预览',note(r.note)+field('previewUser','预览身份',r.userId||D().user.id,'select',D().accounts.map(u=>[u.id,u.name+' · '+u.department]))+`<p role="status">${esc(r.user)}：${r.visible?'当前条件下可见':'当前范围或时间窗口不可见'}</p><section class="ct-workspace ig-preview">${body}</section>`,true);
    document.querySelector('[name=previewUser]').onchange=async e=>{try{showPreview(await api('integration.preview',{entity,id:key,rev,userId:e.target.value}),entity,key,rev)}catch(e){toast(e.message)}};
  }
  async function action(a,id){if(!a.startsWith('ig-'))return false;const op=a.slice(3);if(I().canManage&&await adminUI.action(op,id))return true;if(await mapUI.action(op,id))return true;if(await resultUI.action(op,id))return true;
    if(op==='clear-image'){const f=$('#ig-form');f.elements[id].value='';f.elements[id+'Data'].value='';f.querySelector('[data-ig-image="'+id+'"]').hidden=true;f.querySelector('[data-ig-upload="'+id+'"]').value='';}
    else if(op==='slide-prev'||op==='slide-next'){slide+=op==='slide-next'?1:-1;updateSlide();}
    else if(op==='slide-pause'){carouselPaused=!carouselPaused;document.querySelector('[data-action=ig-slide-pause]').textContent=carouselPaused?'继续轮播':'暂停轮播';}
    else if(op==='preview'){const [entity,key]=id.split(':');const row=entity==='settings'?I().settings:I()[entity].find(r=>r.id===key);const r=await api('integration.preview',{entity,id:key,rev:row.rev});showPreview(r,entity,key,row.rev);}
    else if(op==='versions'){const [entity,key]=id.split(':');const r=await api('integration.versions',{entity,id:key});modal('历史发布版本',note('恢复只覆盖草稿；核对预览后，需再次发布才对用户生效。')+table(['版本','发布时间','发布人','操作'],r.versions.slice().reverse().map(v=>tr('v'+v.version,esc(v.at||'历史记录'),esc(v.actor),B('恢复到草稿','restore',entity+':'+key+':'+v.version+':'+r.rev)))));}
    else if(op==='restore'){const [entity,key,version,rev]=id.split(':');if(confirm('将所选历史版本恢复为草稿？当前发布版本保持不变。'))await send('restore',{entity,id:key,version:Number(version),rev:Number(rev)});}
    else if(op==='tab'){if(route==='integration-results'&&['tools','analysis'].includes(id)&&workspaceUI.openTools(id==='analysis'?'compliance':undefined))return true;nav(route==='integration-settings'?settingsPath(id):usePath({tab:id}));}
    else if(op==='page'){page=Number(id);syncCatalog();}
    else if(op==='reset'){query='';kind='全部';theme='';department='';page=1;syncCatalog();}
    else if(op==='hot'){query=id;page=1;await api('integration.search',{query});syncCatalog();}
    else if(op==='resource-kind'){kind=id;page=1;syncCatalog();}
    else if(op==='work-retry'){workKey='';render();}
    else if(op==='work-filter'){nav(usePath(id==='消息'?{view:'messages',unread:1}:id==='收藏'?{view:'favorites'}:{view:'tasks',status:id}));}
    else if(op==='resource-detail'){const r=I().catalog.find(x=>x.id===id);if(!r)throw Error('资源已下架或不可见');const origins={数据:['资源中心','resources'],服务:['资源中心','resources'],工具:['工具中心','portal-tools'],知识:['智能中心','knowledge'],智能体:['智能中心','agents'],应用场景:['应用中心','app-registry']},origin=origins[r.group];modal(r.name,`<dl class="ig-detail"><dt>资源类型</dt><dd>${esc(r.kind)}</dd><dt>来源中心</dt><dd>${esc(origin?.[0]||'统一目录')}</dd><dt>提供部门</dt><dd>${esc(r.placement.department||r.source||'未登记')}</dd><dt>更新时间</dt><dd>${esc(r.updated||'未登记')}</dd><dt>区域 / 主题</dt><dd>${esc(r.placement.region||r.region||'未登记')} · ${esc(r.placement.theme||'未分类')}</dd></dl><div class="actions">${B('进入使用 / 申请','open',id)}${r.placement.manual?link('使用手册',r.placement.manual):''}${I().canManage&&origin?link('到原中心维护','#/admin/'+origin[1]):''}</div>`);}
    else if(op==='open'){closeModal();sessionStorage.setItem('ig-return-'+D().user.id,location.hash);const r=await api('integration.open',{id});if(r.action){await ctx.loadOnly();await ctx.perform(r.action,r.id);}else if(route==='integration-results'&&id.startsWith('app:')){nav('/admin/integration-results?'+new URLSearchParams({...Object.fromEntries(params()),tab:'scenes',app:id.slice(4)}));}else if(route==='integration-results'&&I().results.tools.some(t=>t.id===id)&&id.startsWith('resource:')){await ctx.loadOnly();const resourceId=id.slice('resource:'.length),resource=D().resources.find(t=>t.id===resourceId);await ctx.perform(resource?.access==='已授权'?'preview':'resource',resourceId);}else if(route==='integration-results'&&id.startsWith('tool:')&&r.target?.startsWith('/front/capabilities/')){const toolId=decodeURIComponent(r.target.slice('/front/capabilities/'.length));nav('/admin/integration-results?'+new URLSearchParams({...Object.fromEntries(params()),tab:'tools',tool:toolId}));}else nav(r.target);}
    else if(op==='favorite'){await api('centers.favorite',{id});await ctx.reload();}
    else if(op==='message')showMessage(I().messages.find(m=>m.id===id));
    else if(op==='read')await send('message.read',{id});
    else if(op==='edit'){const [entity,key]=id.split(':');editor(entity,key);}
    else if(['publish','disable','delete'].includes(op)){const [entity,key]=id.split(':');const r=I()[entity].find(x=>x.id===key);if(op!=='delete'||confirm('删除这条未发布草稿？'))await send(op,{entity,id:key,rev:r.rev});}
    else if(op==='settings'){const s=I().settings;form('门户基础设置',field('title','门户标题',s.title)+field('subtitle','副标题',s.subtitle)+field('theme','主题',s.theme,'select',[['green','自然绿'],['blue','政务蓝']])+imageEditor('background','背景图片',s.background)+field('bannerAutoplay','启用Banner轮播',s.bannerAutoplay||false,'check')+field('bannerSeconds','轮播间隔（3～30秒）',s.bannerSeconds||6,'number'),v=>{return send('settings.save',{rev:s.rev,values:v})});}
    else if(op==='policy'){const s=I().settings;form('查询范围策略',field('maxAreaHa','查询面积上限（公顷）',s.maxAreaHa,'number')+[...new Set(D().accounts.map(u=>u.role))].map(role=>field('roleLimit_'+role,role+' · 公顷上限（空白继承）',s.roleAreaLimits?.[role]??'','number')).join(''),v=>{const roleAreaLimits={};for(const [k,n] of Object.entries(v))if(k.startsWith('roleLimit_')&&n>0)roleAreaLimits[k.slice(10)]=n;return send('policy.save',{rev:s.rev,values:{maxAreaHa:v.maxAreaHa,roleAreaLimits}});});}
    else if(op==='policy-publish')await send('policy.publish',{rev:I().settings.rev});
    else if(op==='settings-publish')await send('settings.publish',{rev:I().settings.rev});
    else if(op==='placement'){const r=I().catalog.find(x=>x.id===id),p=r.placement;form('展示分类 · '+r.name,field('theme','场景主题',p.theme||'','select',[['','不设主题'],...I().themes])+field('department','提供部门',p.department||r.source)+field('region','展示行政区',p.region||r.region)+field('manual','使用手册地址',p.manual),v=>send('placement',{id,rev:p.rev||0,values:v}));}
    else if(op==='preferences'){const p=I().preferences,rows=I().catalog.filter(r=>D().centers.favorites.includes(r.id));form('个人使用配置',field('todoStatus','任务显示',p.todoStatus,'select',['全部','待办','正常','已办','逾期','预警'])+field('metrics','看板指标（当前来源：本人工作记录）',p.metrics,'multi',['待办','正常','逾期','预警','已办','消息','收藏',...I().dashboard.map(r=>[r.id,r.name])])+field('refreshSeconds','刷新频率（秒）',p.refreshSeconds,'number')+field('notify','启用通知提示',p.notify,'check')+field('popup','允许公告弹窗',p.popup,'check')+field('taskPopup','任务提醒',p.taskPopup,'check')+field('taskReminderStatuses','任务提醒范围',p.taskReminderStatuses,'multi',['正常','逾期','预警'])+field('quietStart','免打扰开始',p.quietStart,'time')+field('quietEnd','免打扰结束',p.quietEnd,'time')+`<h3 class="ct-full">收藏分组和顺序</h3>`+rows.map((r,i)=>field('group_'+r.id,r.name+' · 分组',p.groups[r.id]||'')+field('rank_'+r.id,'排序（数值小优先）',p.order.includes(r.id)?p.order.indexOf(r.id):i+100,'number')).join(''),v=>{const groups={},order=rows.slice().sort((a,b)=>v['rank_'+a.id]-v['rank_'+b.id]).map(r=>r.id);for(const r of rows)groups[r.id]=v['group_'+r.id];return send('preferences',{rev:p.rev,values:{todoStatus:v.todoStatus,metrics:v.metrics,refreshSeconds:v.refreshSeconds,notify:v.notify,popup:v.popup,taskPopup:v.taskPopup,taskReminderStatuses:v.taskReminderStatuses,quietStart:v.quietStart,quietEnd:v.quietEnd,order,groups}})});}
    else if(op==='inspect'){await api('integration.inspect',{});monitorData=null;render();}
    else if(op==='peer-edit'){const r=I().peers.find(x=>x.id===id)||{};form('接入对象配置',field('name','名称',r.name)+field('kind','对接类型',r.kind||({national:'国家对接',horizontal:'横向联动',vertical:'纵向交换'}[tab]),'select',['国家对接','横向联动','纵向交换'])+field('direction','交换方向',r.direction||'双向','select',['导入','导出','双向'])+field('endpoint','HTTPS端点',r.endpoint)+field('authClientId','认证客户端',r.authClientId||'','select',[['','未配置'],...D().platform.authClients.map(x=>[x.id,x.name])])+field('contact','联系人',r.contact)+field('mapping','字段映射JSON',r.mapping||{id:'id',name:'name',kind:'kind',url:'url'},'json'),v=>send('peer.save',{id,rev:r.rev,values:v}));}
    else if(op==='exchange-import')form('导入交换清单',note('整批验证，失败保留记录；成功数据作为接入清单保存，不自动发布为可用资源。')+field('rows','JSON数组',[{id:'external-1',name:'外部资源示例',kind:'图层服务',url:'https://example.org/service'}],'json'),v=>send('exchange.import',{id,rows:v.rows}));
    else if(op==='exchange-export'){const r=await api('integration.exchange.export',{id});const url=URL.createObjectURL(new Blob([r.content],{type:r.mime}));const a=document.createElement('a');a.href=url;a.download=r.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);await ctx.reload();}
    else if(op==='exchange-detail'){const r=I().exchanges.find(x=>x.id===id);modal(r.name,table(['标识','名称','类型','入口'],r.rows.map(x=>tr(esc(x.id),esc(x.name),esc(x.kind),esc(x.url)))));}
    else if(op==='tenant-edit'||op==='tenant-child'){const old=op==='tenant-edit'?I().tenants.find(t=>t.id===id):null,parent=op==='tenant-child'?I().tenants.find(t=>t.id===id):I().tenants.find(t=>t.id===old.parentId);form(old?'编辑租户':'创建下级租户',field('name','名称',old?.name)+field('region','行政区',old?.region)+field('permissions','向下开放的权限模板',old?.permissions||['read','write'], 'multi',(parent?.permissions||['read','write','members','children']).map(k=>[k,{read:'查看',write:'资源管理',members:'成员授权',children:'下级管理'}[k]]))+field('enabled','启用',old?.enabled??true,'check'),v=>send('tenant.save',{id:old?.id,rev:old?.rev,values:{...v,parentId:old?.parentId||parent?.id||'',level:old?.level||(parent.level==='自治区'?'盟市':'旗县')}}));}
    else if(op==='tenant-member'){const t=I().tenants.find(t=>t.id===id);form('成员权限 · '+t.name,note('同一成员再次保存会覆盖权限；不选权限即可收回。')+field('userId','成员',D().accounts[0]?.id,'select',D().accounts.map(x=>[x.id,x.name]))+field('permissions','分配权限',['read'],'multi',t.permissions),v=>send('tenant.member',{tenantId:id,rev:I().members.find(m=>m.tenantId===id&&m.userId===v.userId)?.rev,values:v}));}
    else if(op==='tenant-asset')form('新增租户空间资源',field('name','名称')+field('description','说明','', 'textarea')+field('url','HTTPS或本站前台入口'),v=>send('tenant.asset',{tenantId:id,values:v}));
    return true;
  }
  return {navigateApplication:path=>workspaceUI.navigateApplication(path),launchInWorkspace:(...args)=>workspaceUI.launchInWorkspace(...args),render,action,reset(){clearTimeout(timer);clearInterval(carouselTimer);generation++;workspaceUI.destroy();mapUI.destroy();resultUI.reset();}};
}
