import {settingsPath,settingsGroups,sectionFor} from './integration-routes.js';
// Workflow pages share the existing system, publication and task records.
export const integrationSections = [
  ['overview','运行总览','overview'],
  ['presentation','内部门户展示','portal'],['announcements','公告通知','portal'],['placement','展示分类','portal'],
  ['systems','内部系统','connections'],['national','国家对接','connections'],['vertical','纵向交换','connections'],['horizontal','横向联动','connections'],['plans','接入计划','connections'],
  ['tasks','待办同步','tasks'],['receipts','人工状态核对','tasks'],
  ['exceptions','异常处理','monitor'],['monitor','使用统计','monitor'],
  ['access','成果使用授权','access'],['tenants','三级租户','access']
];
export function createIntegrationAdmin(ctx){
  const {esc,field,form,B,table,tr,tag,link,note,api,modal,send}=ctx;
  const D=()=>ctx.state().D, I=()=>D().integration, A=()=>I().administration;
  const params=()=>new URLSearchParams(location.hash.split('?')[1]);
  const path=(tab,filter='',system='')=>'#'+settingsPath(tab,{...(filter?{filter}:{}),...(system?{system}:{})});
  const go=(label,tab,filter='',system='')=>link(label,path(tab,filter,system));
  const systemName=id=>D().centers.systems.find(r=>r.id===id)?.name||I().peers.find(r=>r.id===id)?.name||id;
  const filteredRuns=()=>A().runs.filter(r=>(!params().get('system')||r.systemId===params().get('system'))&&(params().get('filter')!=='failed'||(r.status==='校验失败'&&!r.resolved&&!r.archived)));
  const openFailures=()=>A().runs.filter(r=>r.status==='校验失败'&&!r.resolved&&!r.archived);
  const pending=()=>['contents','announcements'].flatMap(entity=>I()[entity].filter(r=>r.status==='草稿').map(r=>({...r,entity})));
  function sectionNav(tab){const group=sectionFor(tab),selected=params().get('system');const peers=settingsGroups.find(g=>g[0]===group)?.[2]||[];return `<nav class="ig-section-nav" aria-label="集成配置分类">${settingsGroups.map(([key,label,items])=>`<a href="${path(items[0])}" ${key===group?'aria-current="page"':''}>${label}</a>`).join('')}</nav>`+(selected?'':`<nav class="ig-section-nav ig-subnav" aria-label="配置内容">${peers.map(key=>`<a href="${path(key)}" ${key===tab?'aria-current="page"':''}>${esc(integrationSections.find(x=>x[0]===key)?.[1]||'查询范围策略')}</a>`).join('')}</nav>`);}
  function filters(tab,extra=''){return `<form id="ig-admin-filter" class="ig-admin-filter">${field('system','来源系统',params().get('system')||'','select',[['','全部系统'],...D().centers.systems.filter(r=>r.todoEnabled).map(r=>[r.id,r.name])])}${extra}<button class="btn primary" type="submit">筛选</button>${go('清除筛选',tab)}</form>`;}
  function runTable(rows){return table(['同步批次 / 来源','时间 / 映射版本','处理结果','操作'],rows.slice().reverse().map(r=>tr(`<strong>${esc(r.name)}</strong><small>${esc(r.id)}</small>`,esc(r.createdAt)+'<small>映射 v'+r.adapterRev+'</small>',tag(r.status)+(r.resolved?tag('重试已恢复'):'')+(r.archived?tag('人工归档'):'')+`<small>新增 ${r.added} · 更新 ${r.updatedCount} · 跳过 ${r.skipped} · 错误 ${r.errorCount}</small>`,B('查看批次','task-detail',r.id)+(r.status==='校验失败'&&!r.resolved&&!r.archived?B('按当前映射重试','task-retry',r.id)+B('记录处置','task-archive',r.id):''))));}
  function overview(){
    const systems=D().centers.systems,issues=A().systemIssues,failures=openFailures(),receipts=A().receipts.filter(r=>r.status!=='人工核对一致');
    const cards=[['待完善接入配置',issues.length,'systems','incomplete','共 '+systems.length+' 个内部系统'],['待处理同步失败',failures.length,'tasks','failed','成功重试后自动移出'],['待核对办理状态',receipts.length,'receipts','pending','按当前任务版本核对'],['待发布内容',pending().length,'presentation','draft','门户展示与公告草稿']];
    return `<div class="ig-admin-metrics">${cards.map(([label,value,tab,filter,description])=>`<a class="panel ig-admin-metric" href="${path(tab,filter)}"><span>${label}</span><strong>${value}</strong><small>${description} <b>查看 →</b></small></a>`).join('')}</div><div class="ig-admin-columns"><section class="panel ct-panel"><h2>接入进度</h2><p>${systems.length-issues.length} / ${systems.length} 个系统已具备必填配置</p><progress max="${systems.length||1}" value="${systems.length-issues.length}"></progress><p class="muted">配置完整度与外部联通状态分别记录。</p>${go('查看内部系统','systems')}${go('管理接入计划','plans')}${go('国家与省级对接','national')}<h2>接入计划</h2>${I().plans.slice(-3).reverse().map(r=>`<div class="ig-attention"><strong>${esc(r.name)}</strong><small>${esc(r.owner)} · ${esc(r.phase)} · ${esc(r.dueAt||'未设日期')}</small>${B('查看计划','plan-edit',r.id)}</div>`).join('')||'<p class="muted">尚未制定接入计划，可按系统明确负责人、联调阶段与完成日期。</p>'}</section><section class="panel ct-panel"><h2>需要处理</h2>${issues.slice(0,3).map(r=>`<div class="ig-attention"><strong>${esc(r.name)}</strong><small>${esc(r.reason)} · 负责人：${esc(r.owner)}</small>${B('查看接入详情','system-detail',r.id)}</div>`).join('')||'<p>内部系统必填配置已完成。</p>'}${go('查看全部异常','exceptions')}</section></div><section class="panel ct-panel"><h2>最近待办同步</h2>${runTable(A().runs.slice(-5))}${go('进入待办同步','tasks')}</section><section class="panel ct-panel"><h2>资源概况</h2><div class="ig-resource-summary">${Object.entries(I().metrics.counts).map(([k,v])=>`<a href="${path('placement',k)}">${esc(k)} <strong>${v}</strong></a>`).join('')}</div></section>`;
  }
  function tasks(){const selected=params().get('system');return note('导入来源数据后进行整批校验；相同来源版本重复提交会跳过，旧版本与冲突版本会拒绝。失败批次保留并支持按当前映射重试。')+filters('tasks',field('filter','同步结果',params().get('filter')||'','select',[['','全部结果'],['failed','未恢复失败']]))+table(['待办来源','接入人 / 最近同步','配置与操作'],D().centers.systems.filter(r=>r.todoEnabled&&(!selected||r.id===selected)).map(r=>{const last=A().runs.filter(x=>x.systemId===r.id).at(-1);return tr(`<strong>${esc(r.name)}</strong><small>本地导入 · ${esc(r.status)}</small>`,esc(r.contact||'未指定负责人')+'<small>'+(last?esc(last.createdAt)+' · '+esc(last.status):'尚无同步批次')+'</small>',B('接入详情','system-detail',r.id)+B('接收人与状态映射','task-adapter',r.id)+B('导入来源任务','task-import',r.id));}))+`<h2>同步批次</h2>`+runTable(filteredRuns());}
  function receipts(){const rows=A().receipts.filter(r=>(!params().get('system')||r.systemId===params().get('system'))&&(params().get('filter')!=='pending'||r.status!=='人工核对一致'));return note('记录来源系统与当前本地任务的人工核对结果。不会修改来源任务或伪造自动回传回执；任务版本变化后需重新核对。')+filters('receipts',field('filter','核对状态',params().get('filter')||'','select',[['','全部记录'],['pending','待核对 / 不一致']]))+table(['任务 / 来源','本地状态 / 来源版本','核对结果','操作'],rows.map(r=>tr(`<strong>${esc(r.name)}</strong><small>${esc(systemName(r.systemId))} · ${esc(r.externalId)}</small>`,tag(r.localStatus)+'<small>来源版本 '+esc(r.sourceVersion??'旧版未记录')+'</small>',tag(r.status)+(r.last?'<small>'+esc(r.last.evidence)+' · '+esc(r.last.actor)+'</small>':''),B('记录人工核对','task-receipt',r.taskId)+B('查看任务与核对历史','task-history',r.taskId))));}
  function exceptions(){const failures=openFailures();const exchanges=I().exchanges.filter(r=>r.status==='导入失败');return `<h2>接入配置缺失 · ${A().systemIssues.length}</h2>`+table(['系统','问题','负责人','处理'],A().systemIssues.map(r=>tr(esc(r.name),esc(r.reason),esc(r.owner),B('查看接入详情','system-detail',r.id))))+`<h2>未恢复待办同步失败 · ${failures.length}</h2>`+runTable(failures)+`<h2>交换失败历史 · ${exchanges.length}</h2>`+table(['对象','时间','错误','处理'],exchanges.map(r=>tr(esc(r.name),esc(r.at),esc(r.error),go('前往对应接入页',({国家对接:'national',纵向交换:'vertical',横向联动:'horizontal'})[I().peers.find(p=>p.id===r.peerId)?.kind]||'vertical'))))+`<p class="muted">交换失败保留为历史记录；此列表不将一次后续交换成功视为所有历史问题均已解决。</p>`;}
  function access(){return link('内部工作空间准入 · 身份管理','#/admin/identity')+note('成果使用授权只开放后台成果工作区，不授予门户发布、接入配置或租户管理权限。数据可见范围与资源使用授权继续独立校验。')+table(['用户 / 岗位','成果查看','空间查询分析','操作'],D().accounts.filter(u=>u.role!=='平台管理员').map(u=>{const a=A().access[u.id]||{};return tr(esc(u.name)+'<small>'+esc(u.role)+'</small>',tag(a.view?'已授权':'未授权'),tag(a.analyze?'已授权':'未授权'),B('设置成果权限','access-edit',u.id));}));}
  function plans(){return B('新增接入计划','plan-edit','','primary')+note('记录接入对象、责任人、计划日期和联调阶段。人工验收依据不等同于系统自动探测结果。')+table(['计划 / 对象','负责人 / 部门','计划日期','阶段','操作'],I().plans.filter(r=>!params().get('system')||r.target===params().get('system')).map(r=>tr(esc(r.name)+'<small>'+esc(systemName(r.target))+'</small>',esc(r.owner)+'<small>'+esc(r.department)+'</small>',esc(r.dueAt||'未设置'),tag(r.phase),B('查看 / 编辑','plan-edit',r.id))));}
  function draftQueue(){return `<section class="panel ct-panel"><h2>待发布内容 · ${pending().length}</h2>${table(['内容','所属栏目','操作'],pending().map(r=>tr(esc(r.name),r.entity==='contents'?'内部门户展示':'公告通知',B('编辑','edit',r.entity+':'+r.id)+B('预览','preview',r.entity+':'+r.id))))}</section>`;}
  function render(tab){return ({overview,tasks,receipts,exceptions,access,plans})[tab]?.()??null;}
  function bind(tab){const nav=document.querySelector('.ig-section-nav'),active=nav?.querySelector('[aria-current=page]');if(active&&nav.scrollWidth>nav.clientWidth)nav.scrollLeft=active.offsetLeft-nav.offsetLeft-12;const f=document.querySelector('#ig-admin-filter');if(f)f.onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(f));location.hash=path(tab,v.filter,v.system);};}
  const mappingRows=(mapping,type)=>Object.entries(mapping).map(([key,value])=>`<div class="ig-mapping-row"><input aria-label="来源${type==='user'?'用户标识':'状态'}" value="${esc(key)}" data-mapping-key>${type==='user'?`<select aria-label="平台接收人" data-mapping-value>${D().accounts.map(u=>`<option value="${esc(u.id)}" ${u.id===value?'selected':''}>${esc(u.name)} · ${esc(u.role)}</option>`).join('')}</select>`:`<select aria-label="平台任务状态" data-mapping-value><option ${value==='待办'?'selected':''}>待办</option><option ${value==='已办'?'selected':''}>已办</option></select>`}<button type="button" class="btn small" data-remove-mapping>移除</button></div>`).join('');
  async function action(op,id){
    if(op==='task-archive'){
      const r=A().runs.find(x=>x.id===id);form('处置失败批次',field('kind','处置方式','来源撤回','select',['来源撤回','已另批修正'])+field('replacement','替代成功批次（另批修正时必选）','','select',[['','未选择'],...A().runs.filter(x=>x.systemId===r.systemId&&x.status==='已完成').map(x=>[x.id,x.createdAt+' · '+x.id])])+field('reason','处置依据（至少5字）','','textarea')+note('归档保留原始错误和处置依据，不将失败批次标记为同步成功。'),v=>send('admin.task.archive',{id,rev:r.rev,values:v}));
    }else if(op==='system-detail'){
      ctx.nav(settingsPath('systems',{system:id}));
    }else if(op==='access-edit'){
      const u=D().accounts.find(x=>x.id===id),a=A().access[id]||{rev:0};form('成果使用授权 · '+u.name,field('view','允许查看成果',a.view||false,'check')+field('analyze','允许空间查询分析',a.analyze||false,'check')+note('取消查看时应同时取消分析；资源与行政区权限保持独立。'),v=>send('admin.access.save',{id,rev:a.rev,values:v}));
    }else if(op==='task-adapter'){
      const a=A().adapters[id];form('接收人与状态映射',`<div class="ct-full"><h3>接收人映射</h3><p>未列出的来源用户标识，按同名平台用户ID匹配；匹配不到会阻止整批导入。</p><div id="ig-user-mapping">${mappingRows(a.userMap,'user')}</div><button type="button" class="btn small" data-add-mapping="user">添加接收人映射</button><h3>状态映射</h3><div id="ig-status-mapping">${mappingRows(a.statusMap,'status')}</div><button type="button" class="btn small" data-add-mapping="status">添加状态映射</button></div>`+field('versionField','来源版本字段',a.versionField),v=>{for(const [key,type] of [['userMap','user'],['statusMap','status']]){v[key]=Object.create(null);for(const row of document.querySelectorAll('#ig-'+type+'-mapping .ig-mapping-row')){const k=row.querySelector('[data-mapping-key]').value.trim();if(!k||Object.hasOwn(v[key],k))throw Error('来源映射标识不能为空或重复');v[key][k]=row.querySelector('[data-mapping-value]').value;}}return send('admin.task.adapter',{id,rev:a.rev,values:v});});
      document.querySelector('#ig-form').addEventListener('click',e=>{if(e.target.matches('[data-remove-mapping]'))e.target.closest('.ig-mapping-row').remove();if(e.target.dataset.addMapping){const type=e.target.dataset.addMapping;document.querySelector('#ig-'+type+'-mapping').insertAdjacentHTML('beforeend',mappingRows({'':type==='user'?D().accounts[0]?.id:'待办'},type));}});
    }else if(op==='task-import'){
      const system=D().centers.systems.find(r=>r.id===id),a=A().adapters[id],sample={};for(const [k,f] of Object.entries(system.mapping))sample[f]=({id:'source-task-001',name:'待办同步示例',userId:D().accounts.find(u=>u.role==='业务用户')?.id||D().user.id,status:Object.keys(a.statusMap)[0],createdAt:'',dueAt:'',entry:''})[k]||'';sample[a.versionField]=1;
      form('导入来源任务 · '+system.name,note('按来源字段映射读取，版本须为正整数。整批失败不会写入任何任务；失败批次可查看错误并重试。')+field('payload','来源任务 JSON 数组',[sample],'json'),async v=>{const r=await send('admin.task.import',{systemId:id,payload:v.payload});await action('task-detail',r.id);});
    }else if(op==='task-detail'){
      const r=await api('integration.admin.task.detail',{id});modal('同步批次 · '+r.id,`<p>${tag(r.status)} · ${esc(r.scope)}</p><p>新增 ${r.added} · 更新 ${r.updatedCount} · 跳过 ${r.skipped} · 映射 v${r.adapterRev}</p>${r.retryOf?'<p>重试来源：'+esc(r.retryOf)+'</p>':''}${r.resolution?'<p>人工归档：'+esc(r.resolution.kind)+' · '+esc(r.resolution.reason)+' · '+esc(r.resolution.actor)+'</p>':''}${table(['行号','来源任务','错误原因'],r.errors.map(x=>tr(x.row||'整批',esc(x.externalId),esc(x.reason))))}<details><summary>查看来源数据</summary><pre class="ig-source-data">${esc(typeof r.payload==='string'?r.payload:JSON.stringify(r.payload,null,2))}</pre></details>`,true);
    }else if(op==='task-retry'){
      const r=A().runs.find(x=>x.id===id);const result=await send('admin.task.retry',{id,rev:r.rev});await action('task-detail',result.id);
    }else if(op==='task-receipt'){
      const r=A().receipts.find(x=>x.taskId===id);form('人工核对 · '+r.name,note('当前本地状态：'+r.localStatus+'。请先在来源系统确认实际状态，再记录核对依据。')+field('sourceStatus','来源系统实际状态',r.localStatus,'select',['待办','已办'])+field('evidence','核对依据（至少5字）','','textarea'),v=>send('admin.task.receipt',{id,rev:r.taskRev,values:v}));
    }else if(op==='task-history'){
      const r=await api('integration.admin.task.history',{id});modal('任务与人工核对历史',`<p>${esc(r.task.name)} · 来源版本 ${esc(r.task.sourceVersion??'未记录')}</p>${table(['时间','操作人','核对结果','依据'],r.receipts.slice().reverse().map(x=>tr(esc(x.createdAt),esc(x.actor),tag(x.status)+(x.taskRev===r.task.rev?'':'（历史版本）'),esc(x.evidence))))}`,true);
    }else if(op==='plan-edit'){
      const r=I().plans.find(x=>x.id===id)||{};form('接入计划',field('name','计划名称',r.name)+field('target','接入对象',r.target||params().get('system')||D().centers.systems[0]?.id,'select',[...D().centers.systems,...I().peers].map(x=>[x.id,x.name]))+field('owner','负责人',r.owner)+field('department','责任部门',r.department)+field('dueAt','计划完成日期',r.dueAt,'date')+field('phase','阶段',r.phase||'待准备','select',['待准备','准备中','待联调','联调中','人工验收记录'])+field('note','进展说明',r.note,'textarea')+field('evidence','人工验收依据',r.evidence,'textarea'),v=>send('plan.save',{id:r.id,rev:r.rev,values:v}));
    }else return false;
    return true;
  }
  return {render,bind,action,sectionNav,draftQueue};
}
