import {previewSource} from './previews.js';

export function createToolCenter(ctx){
  const {esc,btn,tag,api,nav}=ctx,D=()=>ctx.state().D;
  const link=(id,label,style='btn')=>`<a class="${style}" href="#/front/capabilities/${encodeURIComponent(id)}">${label}</a>`;
  const source=t=>D().resources.find(r=>r.id===t.resourceId);
  const access=t=>t.resourceId?(source(t)?.access||'资源不可用'):'直接使用';
  function actions(t){
    const status=access(t);
    if(['直接使用','已授权'].includes(status)){
      if(t.engine==='external')return t.id.startsWith('resource:')?(t.hasServiceUrl?btn('打开工具','pub-resource-link',t.resourceId+':serviceUrl','primary small'):tag('入口待配置')):btn('打开工具','pub-external',t.id,'primary small');
      return `<a class="btn primary small" data-tool-use="${esc(t.id)}" href="#/front/capabilities/${encodeURIComponent(t.id)}?view=use">${status==='直接使用'?'直接使用':'开始使用'}</a>`;
    }
    return status==='可申请'?btn(ctx.cart().includes(t.resourceId)?'已加入申请车':'加入申请车','addCart',t.resourceId,'small')+btn('在线申请','tc-apply',t.resourceId,'primary small'):status==='申请中'?'<a class="btn small" href="#/front/applications">查看申请进度</a>':tag(status);
  }
  function rows(){
    const tools=D().portalManagement.tools,linked=new Set(tools.map(t=>t.resourceId));
    const standalone=D().resources.filter(r=>r.type==='工具服务'&&!linked.has(r.id)).map(r=>({id:'resource:'+r.id,name:r.name,category:r.category,description:r.description,provider:r.source,sourceUnit:r.source,region:r.region,resourceId:r.id,engine:'external',module:'外部服务',publisher:r.source,version:r.version,hasServiceUrl:r.hasServiceUrl,apiDescription:r.apiDescription||'该共享资源尚未绑定本地执行组件，请按资源授权和提供方接口说明使用。',contract:{parameters:[],example:{},output:r.outputDescription||'以提供方发布的接口协议为准。'},interfaceType:r.serviceProtocol||'功能接口',publishedAt:r.updated,applicationCount:r.applicationCount||0,directoryName:D().centers?.directories?.find(d=>d.id===D().centers?.sharing?.[r.id]?.directoryId)?.name||'未编目'}));
    return [...tools,...standalone];
  }
  function catalog(){
    const all=rows(),params=new URLSearchParams(location.hash.split('?')[1]||''),value=k=>params.get(k)||'',q=value('q').trim().toLowerCase();
    let visible=all.filter(t=>(!q||[t.name,t.category,t.description,t.provider,t.sourceUnit,t.interfaceType].join(' ').toLowerCase().includes(q))&&['directoryName','sourceUnit','region','category'].every(k=>!value(k)||t[k]===value(k)));
    visible.sort(value('sort')==='最热'?(a,b)=>(b.applicationCount||0)-(a.applicationCount||0)||String(b.publishedAt).localeCompare(String(a.publishedAt)):(a,b)=>String(b.publishedAt).localeCompare(String(a.publishedAt)));
    const select=(key,label)=>`<label class="pub-field"><span>${label}</span><select name="${key}"><option value="">全部（${all.length}）</option>${[...new Set(all.map(t=>t[key]).filter(Boolean))].map(v=>`<option value="${esc(v)}" ${value(key)===v?'selected':''}>${esc(v)}（${all.filter(t=>t[key]===v).length}）</option>`).join('')}</select></label>`;
    return `<header class="pub-heading"><div><span class="pub-eyebrow">工具中心</span><h1>能力服务</h1><p>按目录、数源单位和地市查找工具，查看接口并申请使用。</p></div><div class="actions">${btn('我的申请车 '+ctx.cart().length,'cart','','primary')}<a class="btn" href="#/front/applications">我的申请与授权</a></div></header><form id="tc-filter" class="pub-filter"><label class="pub-field"><span>关键词</span><input name="q" value="${esc(value('q'))}" placeholder="工具名称、介绍、单位或接口类型"></label>${select('directoryName','共享目录')}${select('sourceUnit','部门分类')}${select('region','地市专区')}${select('category','工具类型')}<label class="pub-field"><span>排序</span><select name="sort"><option ${value('sort')!=='最热'?'selected':''}>最新</option><option ${value('sort')==='最热'?'selected':''}>最热</option></select></label><button class="btn primary">查询</button><a class="btn" href="#/front/capabilities">重置</a></form><p role="status">找到 <strong>${visible.length}</strong> 项工具服务 · 热度按申请次数统计</p><div class="pub-grid">${visible.map(t=>`<article class="pub-card"><img class="tc-cover" src="${esc(t.screenshot||previewSource(t))}" alt="${esc(t.name)}${t.screenshot?'工具截图':'功能示意图'}" loading="lazy"><div class="pub-card-body"><small>${esc(t.category)} · ${esc(t.interfaceType)}</small><h2>${link(t.id,esc(t.name),'')}</h2><p>${esc(t.description)}</p><dl class="pub-definition"><dt>数源单位</dt><dd>${esc(t.sourceUnit||t.provider)}</dd><dt>上架时间</dt><dd>${esc(t.publishedAt?.slice(0,10)||'—')}</dd><dt>申请次数</dt><dd>${t.applicationCount||0}</dd></dl><div class="actions">${actions(t)}${link(t.id,'查看详情','btn small')}</div></div></article>`).join('')||'<section class="empty"><h2>没有符合条件的工具</h2><p>请调整关键词或分类条件。</p></section>'}</div>`;
  }
  function detail(t){
    const contract=t.contract||{parameters:[],example:{},output:''},status=access(t),canRun=['直接使用','已授权'].includes(status);
    let example=t.inputExample||JSON.stringify(contract.example,null,2);
    const metadata=[['接口类型',t.interfaceType],['功能模块',t.module],['发布单位',t.publisher||t.provider],['提供方',t.provider],['发布时间',t.publishedAt?.replace('T',' ')],['共享目录',t.directoryName],['地市',t.region],['申请次数',t.applicationCount||0],['版本','v'+t.version]];
    return `<section class="panel pub-content tc-detail"><div class="pub-section-head"><h1>${esc(t.name)}</h1><a class="btn" href="#/front/capabilities">返回工具目录</a></div><dl class="pub-definition">${metadata.map(([key,v])=>`<dt>${key}</dt><dd>${esc(v??'—')}</dd>`).join('')}</dl><p>${esc(t.description)}</p>${t.screenshot?`<img class="tc-detail-image" src="${esc(t.screenshot)}" alt="${esc(t.name)}工具截图">`:''}<div class="actions">${actions(t)}</div><h3>接口说明</h3><p>${esc(t.apiDescription||'通过本平台在线接口提交 JSON 请求，调用前校验工具角色权限与关联资源授权。')}</p><div class="table-scroll"><table><thead><tr><th>请求参数</th><th>类型</th><th>必填</th><th>说明</th></tr></thead><tbody>${contract.parameters.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.type)}</td><td>${esc(p.required)}</td><td>${esc(p.description)}</td></tr>`).join('')||'<tr><td colspan="4">尚未登记请求参数，请由提供方补充接口说明。</td></tr>'}</tbody></table></div><h3>返回结果</h3><p>${esc(t.outputDescription||contract.output)}</p><details><summary>返回示例（结构说明）</summary><pre class="tc-json">${esc(JSON.stringify(contract.returnExample||{},null,2))}</pre></details><h3>请求示例与在线测试</h3>${t.engine==='external'?`<p>接口协议与返回结构由提供方维护。</p>${t.id.startsWith('resource:')?(canRun&&t.hasServiceUrl?btn('打开工具服务','pub-resource-link',t.resourceId+':serviceUrl','primary'):'<p>获得授权并配置服务入口后可在线使用。</p>'):'<p>使用下方已登记的外部工具入口。</p>'}`:`<p>${t.engine.startsWith('spatial-')?'入库、编辑和查询作用于本地工作图层；写操作请先查询最新 revision。':'支持 WKT、GeoJSON 与每行 x,y 或 点号,x,y 的界址点文本。坐标系须与输入一致。'}</p><form id="tc-test" data-id="${esc(t.id)}"><label class="pub-field"><span>请求 JSON</span><textarea name="payload" rows="12" required>${esc(example)}</textarea></label><label class="pub-field"><span>导入几何文件（WKT、TXT、CSV、GeoJSON；填入 geometry）</span><input id="tc-geometry-file" type="file" accept=".wkt,.txt,.csv,.json,.geojson"></label><button class="btn primary" ${canRun?'':'disabled'} type="submit">${canRun?'在线测试':'获得授权后可测试'}</button></form><div id="tc-output" aria-live="polite"></div>`}</section>`;
  }
  function bind(){
    const filter=document.querySelector('#tc-filter');if(filter)filter.onsubmit=e=>{e.preventDefault();nav('/front/capabilities?'+new URLSearchParams(new FormData(filter)));};
    const form=document.querySelector('#tc-test');if(!form)return;
    const file=document.querySelector('#tc-geometry-file');file.onchange=async()=>{try{const f=file.files[0];if(!f)return;if(f.size>180000)throw Error('几何文件不能超过180KB');const text=await f.text();let geometry=text;if(/^[\s]*[\[{]/.test(text))geometry=JSON.parse(text);const payload=JSON.parse(form.elements.payload.value);payload.geometry=geometry;form.elements.payload.value=JSON.stringify(payload,null,2);}catch(error){ctx.toast(error.message);}};
    form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');if(button.disabled)return;button.disabled=true;const output=document.querySelector('#tc-output');output.textContent='正在执行…';try{const result=await api('portal.toolRun',{id:form.dataset.id,payload:JSON.parse(form.elements.payload.value)});if(!form.isConnected)return;output.innerHTML=`<h3>返回结果</h3><pre class="tc-json">${esc(JSON.stringify(result,null,2))}</pre><button class="btn small" id="tc-export-result" type="button">下载结果 JSON</button>`;document.querySelector('#tc-export-result').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='工具计算结果.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};}catch(error){if(form.isConnected)output.textContent='执行失败：'+error.message;}finally{button.disabled=false;}};
  }
  return {catalog,detail,bind,access,find:id=>rows().find(t=>t.id===id)};
}
